### ISSUE TITLE
geth appears to be completely stopped, and continues reporting the same output

### ISSUE THREAD

**Issue by tcoulter** [ethereum/go-ethereum#1513]
Output's below. I'm not sure where to go from here.
```
I0723 08:11:45.173836   12805 chain_manager.go:773] Transaction w/ invalid nonce. tx=78976  state=0)
I0723 08:11:45.183061   12805 downloader.go:253] Synchronisation failed: block downloading canceled (requested)
I0723 08:11:49.840367   12805 chain_manager.go:772] Bad block #969692 (3bae22fb6f1581e447f2bb14807ca48e6dcfa7246c9dc37efffadc4f62cc0342)
I0723 08:11:49.840444   12805 chain_manager.go:773] Transaction w/ invalid nonce. tx=78976  state=0)
I0723 08:11:49.840648   12805 downloader.go:253] Synchronisation failed: hash fetching canceled (requested)
I0723 08:11:51.162382   12805 chain_manager.go:772] Bad block #969692 (3bae22fb6f1581e447f2bb14807ca48e6dcfa7246c9dc37efffadc4f62cc0342)
I0723 08:11:51.162407   12805 chain_manager.go:773] Transaction w/ invalid nonce. tx=78976  state=0)
I0723 08:11:51.162490   12805 downloader.go:253] Synchronisation failed: block downloading canceled (requested)
I0723 08:11:56.661449   12805 chain_manager.go:772] Bad block #969692 (3bae22fb6f1581e447f2bb14807ca48e6dcfa7246c9dc37efffadc4f62cc0342)
I0723 08:11:56.661502   12805 chain_manager.go:773] Transaction w/ invalid nonce. tx=78976  state=0)
I0723 08:11:56.661669   12805 downloader.go:253] Synchronisation failed: hash fetching canceled (requested)
I0723 08:12:00.644072   12805 chain_manager.go:772] Bad block #969692 (3bae22fb6f1581e447f2bb14807ca48e6dcfa7246c9dc37efffadc4f62cc0342)
I0723 08:12:00.644092   12805 chain_manager.go:773] Transaction w/ invalid nonce. tx=78976  state=0)
I0723 08:12:00.644169   12805 downloader.go:253] Synchronisation failed: block downloading canceled (requested)
```

Debian Wheezy
`develop`, commit `adc7ab0dd68c86338c7f4fe65162ab911c715606` (latest as of this writing)

**Comment by tcoulter** [comment]
The workaround was to use `debug.setHead()` in the console to have the geth redownload the chain, but without human intervention geth would have been in an unusable state.

**Comment by miketheguy** [comment]
Got  the same problem at least starting at about 3:00am CET, also the balance in my account dropped from 100k to 27 (wo k;)!?
![bildschirmfoto vom 2015-07-24 06 59 12](https://cloud.githubusercontent.com/assets/13161730/8868875/92c077bc-31dd-11e5-9e44-cf46e8a330c8.png)

**Comment by karalabe** [comment]
Use setHead with a few blocks in the past (100, 1000). If the database issue is recent (did geth crash for you?), reverting to some older state may solve the issue.

**Comment by pureland** [comment]
today I had this problem several times , but only one time I fix the problem by using debug.sethead( 1000 block ago).

**Comment by tcoulter** [comment]
@karalabe setHead() worked for me to resolve it the first time, but it happened again just now. I can keep resolving it manually but this would suggest there's a larger issue at play. 

Here's the log output where my client goes from working to not working. Notice that as the bad blocks show up, it slowly stops importing blocks and ends up eventually not progressing any further. https://gist.github.com/tcoulter/e27a9818907e78bfe482

**Comment by tcoulter** [comment]
This apparently happened to my node along with it. I assume all peers eventually booted me.

<img width="1438" alt="screen shot 2015-07-24 at 2 53 40 pm" src="https://cloud.githubusercontent.com/assets/92629/8885392/d8d07bfe-3213-11e5-9ac6-136aec332ef6.png">

**Comment by tcoulter** [comment]
Also, it appears there's some network effect, as many others are in the same state as well:

<img width="1440" alt="screen shot 2015-07-24 at 2 55 51 pm" src="https://cloud.githubusercontent.com/assets/92629/8885415/20f690ee-3214-11e5-8ab1-ffb3366bc6a0.png">

**Comment by tcoulter** [comment]
@karalabe I'd love for one of your team to review this issue. The fact that a good portion of those registered with stats.ethdev.net are receiving the error makes me worried come Frontier.

**Comment by tcoulter** [comment]
Of course, I'm happy to help however possible.

**Comment by miketheguy** [comment]
@karalabe
Thanks, I will try next time. Since a recent corrupted bc (due to lack of disk space), leaving me 2 weeks trying to catch up the BC again, I regularly back up .ethereum, whenever I stop geth.
So I restored the latest stable bc and the problem was fixed :)

**Comment by obscuren** [comment]
At some point on your system one of the following things happened:

1. it crashed halfway of writing data
2. it didn't have disk space to write more than half the data
3. there was a level db internal error

Usually setting head or restarting doesn't fix the problem. Do you recall any of the of the above events?

**Comment by fortier** [comment]
@obscuren 
I can only confirm that there was plenty of disk space available in my case.

Sorry, my logs are deleted automatically on restart, so I can't verify for event 1 and 3. Will change my way of doing.

(Related info in duplicate case [#1514](https://github.com/ethereum/go-ethereum/issues/1514))

**Comment by tcoulter** [comment]
@obscuren Both 1 and/or 3 happened on my machine. I'm currently trying to upload an 84gb blockchain backup to S3 for you guys to review, but my internet can't quite seem to handle it (or, it's S3). You can see the crash I receive regularly at #1505.

**Comment by jarradh** [comment]
Had the same thing happen to me just now on 2 separate machines, is there a way geth can auto try and recover from this?

**Comment by douglas-larocca** [comment]
Had this happen running 1.0.1.1 and was able to recover with `debug.setHead(1000)`
