### ISSUE TITLE
geth node (mainnet) crashes every few days

### ISSUE THREAD

**Issue by troowala** [ethereum/go-ethereum#17162]
#### Geth version: 
```
Geth
Version: 1.8.3-stable
Git Commit: 329ac18ef617d0238f71637bffe78f028b0f13f7
Architecture: amd64
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.10
Operating System: linux
GOPATH=
GOROOT=/home/travis/.gimme/versions/go1.10.linux.amd6
```

#### OS & Version: 
```
Ubuntu Server 16.04
```

#### System Specs : 
```
EC2 Instance t2.medium - 2vcpu , 4 GB RAM, 4 GB SWAP , 300GB+ free on the /store volume consisting of geth data 
```

#### Startup Parameters : 
```
screen -dmS "GETH_MAINNET" /store/geth-linux-amd64-1.8.3-329ac18e/geth --datadir=/store/mainnet --rpcapi "personal,web3,eth,net,db,debug" --rpc --rpcaddr "0.0.0.0" --rpccorsdomain "10.10.0.0/16,172.21.0.0/24"
```

#### Actual behaviour
Geth crashes every few days when connected to mainnet. When connected to ropsten it runs fine. No sync issues on mainnet, once the node sync it mostly stays synced but every 4-6 days it crashes.

#### Steps to reproduce the behaviour

Leave geth running without mining connected to mainnet. 

Anyone else facing this issue with geth 1.8.3 and did any version upgrade help ?

Will append the logs shortly as i have just reran geth with --verbosity 4 and console 2 >>logfile.txt but just checking if someone with similar setup ran into this issue.

Thanks

**Comment by karalabe** [comment]
Please try running Gth 1.8.12. There have been many many issues fixed since 1.8.3. I can't say that any of those will fix the issue you are facing, but it doesn't make much sense to debug a release after which we've pushed out 9 more releases.

**Comment by troowala** [comment]
Thanks Peter , will do. 

I have tried upgrading to 1.8.11 recently before the 1.8.12 release but was getting a whole bunch of new errors intermittently  ('RemoteDisconnected('Remote end closed connection without response',)) that i wasnt getting with 1.8.3 henced rolled back to it.

Im happy to give 1.8.12 a try and also provide the logs but in the meantime please find attached logs from 1.8.3 from the last crash. it would be great if someone could provide their thoughts on this and a possible reason why it has been terminating would be great.

[gethlogs.zip](https://github.com/ethereum/go-ethereum/files/2190575/gethlogs.zip)

Possible cause logs.

toor@TR:~$ grep -B10 -A10 -i "fatal error" gethlogs.txt 
DEBUG[07-12|17:26:43] Recalculated downloader QoS values       rtt=2s            confidence=1.000 ttl=6.000006s
DEBUG[07-12|17:26:51] Recalculated downloader QoS values       rtt=2s            confidence=1.000 ttl=6.000006s
DEBUG[07-12|17:27:31] Recalculated downloader QoS values       rtt=2s            confidence=1.000 ttl=6.000006s
DEBUG[07-12|17:28:16] Recalculated downloader QoS values       rtt=2s            confidence=1.000 ttl=6.000006s
DEBUG[07-12|17:29:01] Recalculated downloader QoS values       rtt=2s            confidence=1.000 ttl=6.000006s
DEBUG[07-12|17:29:21] Recalculated downloader QoS values       rtt=2s            confidence=1.000 ttl=6.000006s
DEBUG[07-12|17:30:06] Recalculated downloader QoS values       rtt=2s            confidence=1.000 ttl=6.000006s
DEBUG[07-12|17:30:08] Recalculated downloader QoS values       rtt=2s            confidence=1.000 ttl=6.000006s
DEBUG[07-12|17:30:32] Recalculated downloader QoS values       rtt=2s            confidence=1.000 ttl=6.000006s
DEBUG[07-12|17:31:48] Recalculated downloader QoS values       rtt=2s            confidence=1.000 ttl=6.000006s
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0xf10595, 0x16)
	/home/travis/.gimme/versions/go1.10.linux.amd64/src/runtime/panic.go:619 +0x81
runtime.sysMap(0xc603940000, 0x100000, 0x0, 0x1af8f58)
	/home/travis/.gimme/versions/go1.10.linux.amd64/src/runtime/mem_linux.go:216 +0x20a
runtime.(*mheap).sysAlloc(0x1adf560, 0x100000, 0x7fe67ca950a0)
	/home/travis/.gimme/versions/go1.10.linux.amd64/src/runtime/malloc.go:470 +0xd4
runtime.(*mheap).grow(0x1adf560, 0x1, 0x0)
	/home/travis/.gimme/versions/go1.10.linux.amd64/src/runtime/mheap.go:907 +0x60

Also where is this GOROOT specifiable in geth , i dont have any /home/travis directory on my system , this seems to come from the 1.8.3 version as 1.8.7 version automatically defaults to GOROOT under /usr/lib/go-1.10

**Comment by troowala** [comment]
also is there a better/alternate way to log geth output than ./geth console 2>> logs.txt , this mandates geth console be run and also creates issues running it through screen where you might want to run geth and be able to switch to it anytime.

**Comment by troowala** [comment]
Okay issue persists with 1.8.12 as well. Attached Logs. Have run it without specifying verbosity explicitly.

This is the part captured in the log where it crashes.

grep -A10 -B10 -i "fatal error" gethlogs.0
WARN [07-20|14:39:47.117] Synchronisation failed, dropping peer    peer=00b257ddd0883b23 err="no peers available or all tried for download"
WARN [07-20|14:40:27.028] Synchronisation failed, dropping peer    peer=1c0b30af8b9497da err=timeout
WARN [07-20|14:40:38.187] Synchronisation failed, dropping peer    peer=15167044ca2e6d71 err=timeout
WARN [07-20|14:40:56.749] Synchronisation failed, dropping peer    peer=1c0b30af8b9497da err=timeout
WARN [07-20|14:41:27.762] Synchronisation failed, retrying         err="block body download canceled (requested)"
INFO [07-20|14:43:15.994] Imported new chain segment               blocks=1  txs=273  mgas=7.997   elapsed=1m11.335s  mgasps=0.112  number=5996012 hash=d96c6e…eb2cdd cache=267.65mB
INFO [07-20|14:43:59.663] Imported new chain segment               blocks=1  txs=172  mgas=7.980   elapsed=43.668s    mgasps=0.183  number=5996013 hash=67ee0c…d8346c cache=268.19mB
INFO [07-20|15:02:19.658] Regenerated local transaction journal    transactions=0 accounts=0
INFO [07-20|16:15:56.450] Regenerated local transaction journal    transactions=0 accounts=0
INFO [07-20|17:01:19.087] Regenerated local transaction journal    transactions=0 accounts=0
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0xf4bfcb, 0x16)
        /home/travis/.gimme/versions/go1.10.3.linux.amd64/src/runtime/panic.go:616 +0x81
runtime.sysMap(0xc5f6ef0000, 0x1100000, 0xc420134d00, 0x1b52758)
        /home/travis/.gimme/versions/go1.10.3.linux.amd64/src/runtime/mem_linux.go:216 +0x20a
runtime.(*mheap).sysAlloc(0x1b38e00, 0x1100000, 0xc41fffd33f)
        /home/travis/.gimme/versions/go1.10.3.linux.amd64/src/runtime/malloc.go:470 +0xd4
runtime.(*mheap).grow(0x1b38e00, 0x879, 0x0)
        /home/travis/.gimme/versions/go1.10.3.linux.amd64/src/runtime/mheap.go:907 +0x60

Also attached the logs. 

[gethlogs.zip](https://github.com/ethereum/go-ethereum/files/2217821/gethlogs.zip)

What do you suggest ?

Thanks

**Comment by troowala** [comment]
after increasing RAM to 8GB , swap to 16GB this issue does not happen any more.
