### ISSUE TITLE
Header broke chain ancestry, Synchronisation failed, dropping peer & retrieved hash chain is invalid

### ISSUE THREAD

**Issue by zulhfreelancer** [ethereum/go-ethereum#19052]
### System information

**Geth version**:

```
Geth
Version: 1.8.22-stable
Git Commit: 7fa3509e2eaf1a4ebc12344590e5699406690f15
Architecture: arm
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.11.5
Operating System: linux
GOPATH=/home/pi/go
GOROOT=/home/travis/.gimme/versions/go1.11.5.linux.amd64
```
**OS & version**:

```
Linux raspberrypi-1 4.14.79-v7+ #1159 SMP Sun Nov 4 17:50:20 GMT 2018 armv7l GNU/Linux
```

**Commit hash**:

N/A

**Engine**:

Clique

**Is private blockchain?**:

Yes

### Expected behaviour

Able to sync latest blocks using Geth light client.

### Actual behaviour

I got stucked at `Header broke chain ancestry`, `Synchronisation failed, dropping peer` and `retrieved hash chain is invalid` error.

At first, it managed to download all blocks until around 400,000-ish block. After that, I started to see the errors above.

I tried to replicate it (running Geth 1.8.22-stable light client) on OSX and Ubuntu machine (not Raspberry Pi) and I got the same errors. Restarting Geth and the machines did not solve the problem.

The full node that I'm connected to is running and sealing blocks every 15 seconds just fine. I did open the 30304 port too in the host firewall settings.

<img width="1439" alt="geth" src="https://user-images.githubusercontent.com/3416976/52737322-06e3af80-3007-11e9-8c35-c6db4684f288.png">

This is how I started the sealer node:

```
geth \
    --syncmode="full" \
    --datadir="/home/ubuntu/stand_alone_node" \
    --port="30304" \
    --networkid="88" \
    --ipcpath="/home/ubuntu/stand_alone_node/geth.ipc" \
    --rpc \
    --rpcport="8545" \
    --rpcaddr="0.0.0.0" \
    --rpccorsdomain="*" \
    --rpcvhosts="*" \
    --ws \
    --wsport="8546" \
    --wsaddr="0.0.0.0" \
    --wsorigins="*" \
    --mine \
    --minerthreads="1" \
    --lightserv="50" \
    --lightpeers="100" \
    --unlock="0x..." \
    --password /home/ubuntu/stand_alone_node/sealer-password
```

### Steps to reproduce & backtrace

```
$ cd /home/zulh/my-poa/

$ geth \
  --datadir . \
  --syncmode light \
  init genesis.json # <-- I'm using the same genesis file in full node and light node

$ geth \
  --syncmode light \
  --datadir . \
  --port 30305 \
  --networkid 88 \
  --ipcpath geth.ipc \
  --rpc \
  --rpcport 8547 \
  --rpcaddr 0.0.0.0 \
  --rpccorsdomain "*" \
  --ws \
  --wsport 8548 \
  --wsaddr 0.0.0.0

WARN [02-14|02:50:57.907] Sanitizing cache to Go's GC limits       provided=1024 updated=309
INFO [02-14|02:50:57.914] Maximum peer count                       ETH=0 LES=100 total=25
WARN [02-14|02:50:57.919] Found deprecated node list file /home/zulh/my-poa/geth/static-nodes.json, please use the TOML config file instead.
INFO [02-14|02:50:57.922] Starting peer-to-peer node               instance=Geth/v1.8.22-stable-7fa3509e/linux-arm/go1.11.5
INFO [02-14|02:50:57.922] Allocated cache and file handles         database=/home/zulh/my-poa/geth/lightchaindata cache=154 handles=524288
INFO [02-14|02:50:57.989] Initialised chain configuration          config="{ChainID: 88 Homestead: 1 DAO: <nil> DAOSupport: false EIP150: 2 EIP155: 3 EIP158: 3 Byzantium: 4 Constantinople: <nil>  ConstantinopleFix: <nil> Engine: clique}"
INFO [02-14|02:50:58.023] Loaded most recent local header          number=452224 hash=3034bb…376388 td=880743 age=1w1d18h
INFO [02-14|02:50:58.094] UDP listener up                          net=enode://da006fa220e61658f9a2def4ec91ee186d5b57ecd9b6c1538a1f3c1050a4929aca922dca5e1420e419779c94690728a6d3defba8c68b7cca75aaf72594d255b6@[::]:30305
WARN [02-14|02:50:58.101] Light client mode is an experimental feature
INFO [02-14|02:50:58.108] New local node record                    seq=5 id=784bb25a42074d09 ip=127.0.0.1 udp=30305 tcp=30305
INFO [02-14|02:50:58.108] Started P2P networking                   self=enode://da006fa220e61658f9a2def4ec91ee186d5b57ecd9b6c1538a1f3c1050a4929aca922dca5e1420e419779c94690728a6d3defba8c68b7cca75aaf72594d255b6@127.0.0.1:30305
INFO [02-14|02:50:58.109] IPC endpoint opened                      url=/home/zulh/my-poa/geth.ipc
INFO [02-14|02:50:58.110] HTTP endpoint opened                     url=http://0.0.0.0:8547                              cors=* vhosts=localhost
INFO [02-14|02:50:58.112] WebSocket endpoint opened                url=ws://[::]:8548
INFO [02-14|02:50:58.162] Block synchronisation started
WARN [02-14|02:51:15.195] Header broke chain ancestry              peer=2f2620dad919816a number=454379 hash=ad7ae1…521c51
WARN [02-14|02:51:23.185] Synchronisation failed, dropping peer    peer=2f2620dad919816a err="retrieved hash chain is invalid"
WARN [02-14|02:51:28.478] Header broke chain ancestry              peer=2f2620dad919816a number=454380 hash=7b77bb…e8d388
WARN [02-14|02:51:36.810] Synchronisation failed, dropping peer    peer=2f2620dad919816a err="retrieved hash chain is invalid"
WARN [02-14|02:51:58.505] Header broke chain ancestry              peer=2f2620dad919816a number=454382 hash=ba865d…40dc80
WARN [02-14|02:52:09.145] Synchronisation failed, dropping peer    peer=2f2620dad919816a err="retrieved hash chain is invalid"
WARN [02-14|02:52:28.547] Header broke chain ancestry              peer=2f2620dad919816a number=454384 hash=685cbc…a9f316
WARN [02-14|02:52:36.853] Synchronisation failed, dropping peer    peer=2f2620dad919816a err="retrieved hash chain is invalid"
WARN [02-14|02:52:58.652] Header broke chain ancestry              peer=2f2620dad919816a number=454386 hash=eb8903…ac72db
WARN [02-14|02:53:09.046] Synchronisation failed, dropping peer    peer=2f2620dad919816a err="retrieved hash chain is invalid"
WARN [02-14|02:53:28.708] Header broke chain ancestry              peer=2f2620dad919816a number=454388 hash=498f79…b5e439
WARN [02-14|02:53:36.857] Synchronisation failed, dropping peer    peer=2f2620dad919816a err="retrieved hash chain is invalid"
WARN [02-14|02:53:58.701] Header broke chain ancestry              peer=2f2620dad919816a number=454390 hash=3451c3…04cd19
WARN [02-14|02:54:09.161] Synchronisation failed, dropping peer    peer=2f2620dad919816a err="retrieved hash chain is invalid"
WARN [02-14|02:54:28.797] Header broke chain ancestry              peer=2f2620dad919816a number=454392 hash=fbf7fd…c595a5
WARN [02-14|02:54:36.919] Synchronisation failed, dropping peer    peer=2f2620dad919816a err="retrieved hash chain is invalid"
WARN [02-14|02:54:58.856] Header broke chain ancestry              peer=2f2620dad919816a number=454394 hash=d1d619…fbbc2f
WARN [02-14|02:55:09.288] Synchronisation failed, dropping peer    peer=2f2620dad919816a err="retrieved hash chain is invalid"
WARN [02-14|02:55:28.916] Header broke chain ancestry              peer=2f2620dad919816a number=454396 hash=7319e8…24ec39
WARN [02-14|02:55:37.015] Synchronisation failed, dropping peer    peer=2f2620dad919816a err="retrieved hash chain is invalid"
WARN [02-14|02:55:58.982] Header broke chain ancestry              peer=2f2620dad919816a number=454398 hash=7903a0…909107
WARN [02-14|02:56:09.163] Synchronisation failed, dropping peer    peer=2f2620dad919816a err="retrieved hash chain is invalid"
WARN [02-14|02:56:29.024] Header broke chain ancestry              peer=2f2620dad919816a number=454400 hash=426edd…73c98b
WARN [02-14|02:56:37.193] Synchronisation failed, dropping peer    peer=2f2620dad919816a err="retrieved hash chain is invalid"
WARN [02-14|02:56:59.082] Header broke chain ancestry              peer=2f2620dad919816a number=454402 hash=47ce07…b11a7f
WARN [02-14|02:57:09.449] Synchronisation failed, dropping peer    peer=2f2620dad919816a err="retrieved hash chain is invalid"
WARN [02-14|02:57:29.136] Header broke chain ancestry              peer=2f2620dad919816a number=454404 hash=b3e8ee…24ec7d
WARN [02-14|02:57:37.191] Synchronisation failed, dropping peer    peer=2f2620dad919816a err="retrieved hash chain is invalid"
WARN [02-14|02:57:59.194] Header broke chain ancestry              peer=2f2620dad919816a number=454406 hash=7fe68d…2ac88f
WARN [02-14|02:58:09.520] Synchronisation failed, dropping peer    peer=2f2620dad919816a err="retrieved hash chain is invalid"
WARN [02-14|02:58:29.245] Header broke chain ancestry              peer=2f2620dad919816a number=454408 hash=08c7c1…fa0e1c
WARN [02-14|02:58:37.239] Synchronisation failed, dropping peer    peer=2f2620dad919816a err="retrieved hash chain is invalid"
WARN [02-14|02:58:59.315] Header broke chain ancestry              peer=2f2620dad919816a number=454410 hash=238f3d…3fbbd1
WARN [02-14|02:59:09.635] Synchronisation failed, dropping peer    peer=2f2620dad919816a err="retrieved hash chain is invalid"
WARN [02-14|02:59:29.369] Header broke chain ancestry              peer=2f2620dad919816a number=454412 hash=d1ff45…17dad5
WARN [02-14|02:59:37.154] Synchronisation failed, dropping peer    peer=2f2620dad919816a err="retrieved hash chain is invalid"
```

Any idea how to fix this issue? Thank you in advance! 🙏🏼🙏🏼🙏🏼

**Comment by cyberfab007** [comment]
I am having this same issue    

Sealer Node VERSION: Ubuntu 18.04
   instance=Geth/chain1_data/v1.8.9-unstable-ab6bdbd9

syncing peers     Ubuntu 18.10  Geth/v1.8.22-stable-7fa3509e/linux-amd64/go1.10.4

                           Windows 10    Geth/v1.8.23-stable-c9427004/windows-amd64/go1.11.5

Syncing wont start unless I mine a 1 block,  so I mine one block and begin. 

I get the same error on both pc's 

Ubuntu - > INFO [02-23|13:47:19.073] Upgrading chain index                    type=bloombits percentage=39
INFO [02-23|13:47:27.234] Upgrading chain index                    type=bloombits percentage=58
INFO [02-23|13:47:35.347] Upgrading chain index                    type=bloombits percentage=79
INFO [02-23|13:47:42.960] Finished upgrading chain index           type=bloombits
INFO [02-23|13:48:52.868] Block synchronisation started 
WARN [02-23|13:48:53.729] Header broke chain ancestry              peer=78479c35836a7347 number=743863 hash=837a53…b231be
WARN [02-23|13:49:05.897] Header broke chain ancestry              peer=78479c35836a7347 number=755837 hash=f42b94…e858e5
WARN [02-23|13:49:06.094] Synchronisation failed, dropping peer    peer=78479c35836a7347 err="retrieved hash chain is invalid"


Windows -  Exactly the same blocks , same result 


eth.syncing
{
  currentBlock: 741760,
  highestBlock: 743862,
  knownStates: 519,
  pulledStates: 519,
  startingBlock: 743781
}

Sometimes I can get it as close as 64 blocks , but then it just hangs, with these errors, I have tried syncing over and over again in different modes. Also , Since I was able to do mining on this node, I was able to mine higher block number say 860k and was getting the same error when syncing but I had the  the peers sync past say 859k blocks , so I restore a back up several days old that had this current block number in the stats above.  Why is it getting stuck at the end like this ?

Any help would be cool.

**Comment by cyberfab007** [comment]
For the record , I let id run over night, with no success, 

This is how I start geth
/root/modified_ethereum/go-ethereum/build/bin/geth --identity "chain1_data" 
                                                    --networkid 2030
                                                    --datadir
                                                    ./coin_chain 
                                                    --rpc 
                                                    --rpcaddr 0.0.0.0 
                                                    --rpcport 9173 
                                                    --port 3500
                                                    --rpccorsdomain "HIDDENIPS"
                                                    --rpcapi 'personal,db,eth,net,web3,txpool,miner' 
                                                    --gasprice 0
                                                    --nat 'any'
                                                    --cache 1024 console

**Comment by cyberfab007** [comment]
"
DEBUG[03-03|14:29:54.279] Skeleton fill terminated                 err="no peers available or all tried for download"
DEBUG[03-03|14:29:54.279] Skeleton chain invalid                   peer=78479c35836a7347 err="no peers available or all tried for download"
DEBUG[03-03|14:29:54.279] Header download terminated               peer=78479c35836a7347
DEBUG[03-03|14:29:54.279] Transaction receipt download terminated  err="receipt download canceled (requested)"
DEBUG[03-03|14:29:54.279] Block body download terminated           err="block body download canceled (requested)"
DEBUG[03-03|14:29:54.280] Synchronisation terminated               elapsed=9.992620648s
WARN [03-03|14:29:54.280] Synchronisation failed, dropping peer    peer=78479c35836a7347 err="retrieved hash chain is invalid"
DEBUG[03-03|14:29:54.280] Removing Ethereum peer                   peer=78479c35836a7347
TRACE[03-03|14:29:54.280] Unregistering sync peer                  peer=78479c35836a7347
DEBUG[03-03|14:29:54.280] Ethereum message handling failed         id=78479c35836a7347 conn=staticdial err=EOF
DEBUG[03-03|14:29:54.745] Ethereum peer connected                  id=c81f968b5526dc24 conn=dyndial    name=Geth/v1.8.17-stable-8bbe7207/linux-amd64/go1.11.1
DEBUG[03-03|14:29:54.829] Ethereum peer connected                  id=f586ca029c2de399 conn=dyndial    name=Geth/v0.1.1-akroma-5fa3ee8c/linux-amd64/go1.10.1
DEBUG[03-03|14:29:54.925] Ethereum peer connected                  id=f5ffa0426af44c9b conn=dyndial    name=Geth/v1.8.18-stable-da645b20/linux-amd64/go1.11.4
DEBUG[03-03|14:29:55.012] Ethereum handshake failed                id=f5ffa0426af44c9b conn=dyndial    err="Genesis block mismatch - d5c14f99b2efaea0 (!= 34be4c6eecd55a5c)"
DEBUG[03-03|14:29:55.094] Ethereum handshake failed                id=f586ca029c2de399 conn=dyndial    err="Genesis block mismatch - 679ee3d5213ddab6 (!= 34be4c6eecd55a5c)"
DEBUG[03-03|14:29:55.304] Ethereum peer connected                  id=f53b114821d393fc conn=inbound    name=GMC/v2.6.2-beta-1d81d6eb/linux-amd64/go1.9.7
DEBUG[03-03|14:29:55.304] Ethereum handshake failed                id=f53b114821d393fc conn=inbound    err="Genesis block mismatch - 4eba28a4ce8dc070 (!= 34be4c6eecd55a5c)"
DEBUG[03-03|14:29:55.626] Ethereum handshake failed                id=c81f968b5526dc24 conn=dyndial    err="Genesis block mismatch - d4e56740f876aef8 (!= 34be4c6eecd55a5c)"
DEBUG[03-03|14:29:55.849] Ethereum peer connected                  id=5509fd5550404b4c conn=inbound    name=Geth/v5.2.1-456053c/linux/go1.9.5
DEBUG[03-03|14:29:55.849] Ethereum handshake failed                id=5509fd5550404b4c conn=inbound    err="Genesis block mismatch - d4e56740f876aef8 (!= 34be4c6eecd55a5c)"
DEBUG[03-03|14:29:56.770] Ethereum peer connected                  id=58880cb765570faf conn=inbound    name=Parity-Ethereum/thomas_haller/v2.2.10-stable-7b1d3e1-20190213/x86_64-linux-gnu/rustc1.32.0
DEBUG[03-03|14:29:56.863] Ethereum handshake failed                id=58880cb765570faf conn=inbound    err="Genesis block mismatch - 3bd79a67e856cd34 (!= 34be4c6eecd55a5c)"
DEBUG[03-03|14:29:57.798] Ethereum peer connected                  id=481b75d7b318877c conn=inbound    name=Geth/v1.8.0-unstable-a98b2cda/linux-amd64/go1.9.2
DEBUG[03-03|14:29:57.799] Ethereum handshake failed                id=481b75d7b318877c conn=inbound    err="Genesis block mismatch - ae45a0dac456d78b (!= 34be4c6eecd55a5c)"
DEBUG[03-03|14:29:58.031] Ethereum peer connected                  id=fc7862450b8acc67 conn=inbound    name=Geth/v0.0.0-stable-f25b22f4/linux-arm64/go1.10.1
DEBUG[03-03|14:29:58.031] Ethereum handshake failed                id=fc7862450b8acc67 conn=inbound    err="Genesis block mismatch - f4961b6a6ac3c564 (!= 34be4c6eecd55a5c)"
DEBUG[03-03|14:29:58.240] Ethereum peer connected                  id=cdd5aff45cda0726 conn=inbound    name="Geth/DigiCoin Testnet Node 1/v1.7.3-stable-4bb3c89d/linux-amd64/go1.9"
DEBUG[03-03|14:29:58.240] Ethereum handshake failed                id=cdd5aff45cda0726 conn=inbound    err="Genesis block mismatch - 8e037ead51ca8940 (!= 34be4c6eecd55a5c)"
DEBUG[03-03|14:29:58.351] Ethereum peer connected                  id=4030c0e5f8291271 conn=inbound    name=Geth/v1.8.14-unstable-99e1a5e0/linux-amd64/go1.10.3
DEBUG[03-03|14:29:58.351] Ethereum handshake failed                id=4030c0e5f8291271 conn=inbound    err="Genesis block mismatch - 6341fd3daf94b748 (!= 34be4c6eecd55a5c)"
DEBUG[03-03|14:29:58.575] Ethereum peer connected                  id=f4c0ae1d551e1c70 conn=dyndial    name=Parity-Ethereum/v2.2.11-stable-8e31051-20190220/x86_64-linux-gnu/rustc1.32.0
DEBUG[03-03|14:29:58.576] Ethereum handshake failed                id=f4c0ae1d551e1c70 conn=dyndial    err=EOF
DEBUG[03-03|14:29:59.160] Ethereum peer connected                  id=f102641dd6c92904 conn=inbound    name=Geth/v1.8.23-stable-c9427004/linux-amd64/go1.10.4
DEBUG[03-03|14:29:59.217] Ethereum peer connected                  id=c39143f98d04e97b conn=dyndial    name=Geth/v1.7.0-unstable-8ba6534b/linux-amd64/go1.7.6
DEBUG[03-03|14:29:59.233] Ethereum handshake failed                id=c39143f98d04e97b conn=dyndial    err="Genesis block mismatch - 614556b2e69440f1 (!= 34be4c6eecd55a5c)"
DEBUG[03-03|14:29:59.772] Ethereum handshake failed                id=f102641dd6c92904 conn=inbound    err=EOF
DEBUG[03-03|14:30:00.649] Recalculated downloader QoS values       rtt=18.75144683s  confidence=1.000 ttl=56.25434049s
DEBUG[03-03|14:30:00.675] Ethereum peer connected                  id=995dbe18829f1aff conn=inbound    name=Geth/v1.7.2-stable-0905eda4/linux-amd64/go1.9.4
DEBUG[03-03|14:30:00.675] Ethereum handshake failed                id=995dbe18829f1aff conn=inbound    err="Genesis block mismatch - c23b4ebccc79e263 (!= 34be4c6eecd55a5c)"
DEBUG[03-03|14:30:02.594] Ethereum peer connected                  id=12f1a467a45338a7 conn=inbound    name=Geth/v0.0.0-stable-f25b22f4/linux-arm64/go1.10.1
DEBUG[03-03|14:30:02.594] Ethereum handshake failed                id=12f1a467a45338a7 conn=inbound    err="Genesis block mismatch - f4961b6a6ac3c564 (!= 34be4c6eecd55a5c)"
DEBUG[03-03|14:30:02.847] Ethereum peer connected                  id=6ba71f60b36c6854 conn=inbound    name=Geth/v1.6.5-stable-cf87713d/linux-amd64/go1.8.3
DEBUG[03-03|14:30:02.849] Ethereum handshake failed                id=6ba71f60b36c6854 conn=inbound    err="Genesis block mismatch - d4e56740f876aef8 (!= 34be4c6eecd55a5c)"
DEBUG[03-03|14:30:04.314] Ethereum peer connected                  id=5be8ef522f0ac2f9 conn=inbound    name=Pirl/v1.0.1-masternode-beta1/linux-amd64/go1.8.5
DEBUG[03-03|14:30:04.318] Ethereum handshake failed                id=5be8ef522f0ac2f9 conn=inbound    err="Genesis block mismatch - 29a742ba74d89fc2 (!= 34be4c6eecd55a5c)"
DEBUG[03-03|14:30:04.899] Ethereum peer connected                  id=f5089cbf8488cc93 conn=inbound    name="Geth/qk_client 1.0.1.126/v1.8.20-stable-24d727b6/windows-amd64/go1.11.2"
DEBUG[03-03|14:30:04.899] Ethereum handshake failed                id=f5089cbf8488cc93 conn=inbound    err="Genesis block mismatch - bd034f687d3173c1 (!= 34be4c6eecd55a5c)"
DEBUG[03-03|14:30:05.247] Ethereum peer connected                  id=78479c35836a7347 conn=staticdial name=Geth/chain1_data/v1.8.9-unstable-ab6bdbd9/linux-amd64/go1.9.4
TRACE[03-03|14:30:05.411] Registering sync peer                    peer=78479c35836a7347
DEBUG[03-03|14:30:05.486] Ethereum peer connected                  id=b2b9d01b3d98e70b conn=inbound    name=Parity-Ethereum/v2.2.9-stable-5d5b372-20190203/x86_64-linux-gnu/rustc1.31.1
DEBUG[03-03|14:30:05.605] Ethereum handshake failed                id=b2b9d01b3d98e70b conn=inbound    err="Genesis block mismatch - a3c565fc15c74788 (!= 34be4c6eecd55a5c)"
DEBUG[03-03|14:30:05.865] Ethereum peer connected                  id=f16210b3dd952009 conn=inbound    name=Geth/v5.4.1-a3d20f6/linux/go1.9.6
DEBUG[03-03|14:30:05.875] Ethereum handshake failed                id=f16210b3dd952009 conn=inbound    err="Genesis block mismatch - d4e56740f876aef8 (!= 34be4c6eecd55a5c)"
DEBUG[03-03|14:30:06.513] Ethereum peer connected                  id=c0f36a924fa35eb3 conn=inbound    name=Parity/v1.6.7-beta-e128418-20170518/x86_64-windows-msvc/rustc1.17.0
DEBUG[03-03|14:30:06.514] Ethereum handshake failed                id=c0f36a924fa35eb3 conn=inbound    err=EOF
DEBUG[03-03|14:30:07.308] Ethereum peer connected                  id=94031199559962e6 conn=inbound    name=Geth/source/linux/go1.9.2
DEBUG[03-03|14:30:07.308] Ethereum handshake failed                id=94031199559962e6 conn=inbound    err="Genesis block mismatch - d4e56740f876aef8 (!= 34be4c6eecd55a5c)"
DEBUG[03-03|14:30:07.573] Ethereum peer connected                  id=cba5c97d148b775d conn=inbound    name=Parity-Ethereum/v2.3.4-beta-0e95db1-20190220/x86_64-linux-gnu/rustc1.32.0
DEBUG[03-03|14:30:07.603] Ethereum handshake failed                id=cba5c97d148b775d conn=inbound    err="Genesis block mismatch - d4e56740f876aef8 (!= 34be4c6eecd55a5c)"
DEBUG[03-03|14:30:09.331] Ethereum peer connected                  id=b1cae8e4ad2583bd conn=inbound    name=Geth/v1.7.2-stable-df4267a2/linux-amd64/go1.10.1
DEBUG[03-03|14:30:09.331] Ethereum handshake failed                id=b1cae8e4ad2583bd conn=inbound    err="Genesis block mismatch - 41777035b53fada4 (!= 34be4c6eecd55a5c)"
DEBUG[03-03|14:30:11.465] Ethereum peer connected                  id=2680fa06b4d1c9eb conn=inbound    name=Geth/e97bbd1b66c91a3e042703ec1a9af9361e7c84d892632cfa995bad96f3fa630b7048c8194e2bbc8984a612db7f5f8ca29be5d807d8abe5db86d5505b62eaa382/v1.8.21-stable-9dc5d1a9/linux-amd64/go1.11.4
DEBUG[03-03|14:30:11.465] Ethereum handshake failed                id=2680fa06b4d1c9eb conn=inbound    err="Genesis block mismatch - f02be695cbd50348 (!= 34be4c6eecd55a5c)"
DEBUG[03-03|14:30:14.287] Synchronising with the network           peer=78479c35836a7347 eth=63 head=5e0d9c…e53e45 td=130761614384582 mode=fast
DEBUG[03-03|14:30:14.287] Retrieving remote chain height           peer=78479c35836a7347
DEBUG[03-03|14:30:14.287] Fetching batch of headers                id=78479c35836a7347 conn=staticdial count=1   fromhash=5e0d9c…e53e45 skip=0   reverse=false
DEBUG[03-03|14:30:14.405] Ethereum peer connected                  id=f5f037bab1654061 conn=inbound    name=GoChain/v3.1.1/linux-amd64/go1.12beta2
DEBUG[03-03|14:30:14.405] Ethereum handshake failed                id=f5f037bab1654061 conn=inbound    err="Genesis block mismatch - 84337e882fad5883 (!= 34be4c6eecd55a5c)"
TRACE[03-03|14:30:14.454] Filtering headers                        peer=78479c35836a7347 headers=1
DEBUG[03-03|14:30:14.454] Remote head header identified            peer=78479c35836a7347 number=747300 hash=5e0d9c…e53e45
DEBUG[03-03|14:30:14.454] Looking for common ancestor              peer=78479c35836a7347 local=747072 remote=747300
TRACE[03-03|14:30:14.454] Span searching for common ancestor       peer=78479c35836a7347 count=12  from=747123 skip=15
DEBUG[03-03|14:30:14.454] Fetching batch of headers                id=78479c35836a7347 conn=staticdial count=12  fromnum=747123 skip=15  reverse=false
DEBUG[03-03|14:30:14.619] Found common ancestor                    peer=78479c35836a7347 number=747171 hash=e0a7d1…a2449b
DEBUG[03-03|14:30:14.619] Downloading block bodies                 origin=747172
DEBUG[03-03|14:30:14.619] Downloading transaction receipts         origin=747172
DEBUG[03-03|14:30:14.619] Directing header downloads               peer=78479c35836a7347 origin=747172
TRACE[03-03|14:30:14.620] Fetching skeleton headers                peer=78479c35836a7347 count=192 from=747172
DEBUG[03-03|14:30:14.620] Fetching batch of headers                id=78479c35836a7347 conn=staticdial count=128 fromnum=747363 skip=191 reverse=false
DEBUG[03-03|14:30:14.788] Filling up skeleton                      from=747172
TRACE[03-03|14:30:14.888] Requesting new batch of data             peer=78479c35836a7347 type=headers   from=747172
DEBUG[03-03|14:30:14.888] Fetching batch of headers                id=78479c35836a7347 conn=staticdial count=192 fromnum=747172 skip=0   reverse=false
WARN [03-03|14:30:15.070] Header broke chain ancestry              peer=78479c35836a7347 number=747301 hash=94bddd…06ad33
TRACE[03-03|14:30:15.071] Skeleton filling not accepted            peer=78479c35836a7347 from=747172
TRACE[03-03|14:30:15.071] Failed to deliver retrieved data         peer=78479c35836a7347 type=headers   err="delivery not accepted"
TRACE[03-03|14:30:15.071] Requesting new batch of data             peer=78479c35836a7347 type=headers   from=747364
DEBUG[03-03|14:30:15.071] Fetching batch of headers                id=78479c35836a7347 conn=staticdial count=192 fromnum=747364 skip=0   reverse=false
TRACE[03-03|14:30:15.252] Peer throughput measurements updated     peer=78479c35836a7347 hps=105.945  bps=0.000 rps=0.000 sps=0.000 miss=0 rtt=18.018122614s
TRACE[03-03|14:30:15.252] Delivered new batch of data              peer=78479c35836a7347 type=headers   count=192
TRACE[03-03|14:30:15.252] Requesting new batch of data             peer=78479c35836a7347 type=headers   from=747556
DEBUG[03-03|14:30:15.252] Fetching batch of headers                id=78479c35836a7347 conn=staticdial count=192 fromnum=747556 skip=0   reverse=false
TRACE[03-03|14:30:15.434] Peer throughput measurements updated     peer=78479c35836a7347 hps=200.766  bps=0.000 rps=0.000 sps=0.000 miss=0 rtt=16.234524012s
TRACE[03-03|14:30:15.434] Delivered new batch of data              peer=78479c35836a7347 type=headers   count=192
TRACE[03-03|14:30:15.434] Requesting new batch of data             peer=78479c35836a7347 type=headers   from=747748
DEBUG[03-03|14:30:15.434] Fetching batch of headers                id=78479c35836a7347 conn=staticdial count=192 fromnum=747748 skip=0   reverse=false
TRACE[03-03|14:30:15.614] Peer throughput measurements updated     peer=78479c35836a7347 hps=287.295  bps=0.000 rps=0.000 sps=0.000 miss=0 rtt=14.629081844s
TRACE[03-03|14:30:15.614] Delivered new batch of data              peer=78479c35836a7347 type=headers   count=192
TRACE[03-03|14:30:15.614] Requesting new batch of data             peer=78479c35836a7347 type=headers   from=747940
DEBUG[03-03|14:30:15.614] Fetching batch of headers                id=78479c35836a7347 conn=staticdial count=192 fromnum=747940 skip=0   reverse=false
TRACE[03-03|14:30:15.794] Peer throughput measurements updated     peer=78479c35836a7347 hps=365.277  bps=0.000 rps=0.000 sps=0.000 miss=0 rtt=13.184166108s
TRACE[03-03|14:30:15.794] Delivered new batch of data              peer=78479c35836a7347 type=headers   count=192
TRACE[03-03|14:30:15.794] Requesting new batch of data             peer=78479c35836a7347 type=headers   from=748132
DEBUG[03-03|14:30:15.794] Fetching batch of headers                id=78479c35836a7347 conn=staticdial count=192 fromnum=748132 skip=0   reverse=false
TRACE[03-03|14:30:15.979] Peer throughput measurements updated     peer=78479c35836a7347 hps=432.699  bps=0.000 rps=0.000 sps=0.000 miss=0 rtt=11.884219991s
TRACE[03-03|14:30:15.979] Delivered new batch of data              peer=78479c35836a7347 type=headers   count=192
TRACE[03-03|14:30:15.979] Requesting new batch of data             peer=78479c35836a7347 type=headers   from=748324
DEBUG[03-03|14:30:15.979] Fetching batch of headers                id=78479c35836a7347 conn=staticdial count=192 fromnum=748324 skip=0   reverse=false
TRACE[03-03|14:30:16.159] Peer throughput measurements updated     peer=78479c35836a7347 hps=496.019  bps=0.000 rps=0.000 sps=0.000 miss=0 rtt=10.713810961s
TRACE[03-03|14:30:16.160] Delivered new batch of data              peer=78479c35836a7347 type=headers   count=192
TRACE[03-03|14:30:16.160] Requesting new batch of data             peer=78479c35836a7347 type=headers   from=748516
DEBUG[03-03|14:30:16.160] Fetching batch of headers                id=78479c35836a7347 conn=staticdial count=192 fromnum=748516 skip=0   reverse=false
TRACE[03-03|14:30:16.339] Peer throughput measurements updated     peer=78479c35836a7347 hps=553.638  bps=0.000 rps=0.000 sps=0.000 miss=0 rtt=9.6603369s
TRACE[03-03|14:30:16.339] Delivered new batch of data              peer=78479c35836a7347 type=headers   count=192
TRACE[03-03|14:30:16.339] Requesting new batch of data             peer=78479c35836a7347 type=headers   from=748708
DEBUG[03-03|14:30:16.339] Fetching batch of headers                id=78479c35836a7347 conn=staticdial count=192 fromnum=748708 skip=0   reverse=false
TRACE[03-03|14:30:16.524] Peer throughput measurements updated     peer=78479c35836a7347 hps=601.893  bps=0.000 rps=0.000 sps=0.000 miss=0 rtt=8.712832615s
TRACE[03-03|14:30:16.524] Delivered new batch of data              peer=78479c35836a7347 type=headers   count=192
TRACE[03-03|14:30:16.524] Requesting new batch of data             peer=78479c35836a7347 type=headers   from=748900
DEBUG[03-03|14:30:16.524] Fetching batch of headers                id=78479c35836a7347 conn=staticdial count=192 fromnum=748900 skip=0   reverse=false
WARN [03-03|14:30:16.702] Header broke chain ancestry              peer=78479c35836a7347 number=748957 hash=f0245c…11be13
TRACE[03-03|14:30:16.702] Skeleton filling not accepted            peer=78479c35836a7347 from=748900
TRACE[03-03|14:30:16.702] Failed to deliver retrieved data         peer=78479c35836a7347 type=headers   err="delivery not accepted"
TRACE[03-03|14:30:16.702] Requesting new batch of data             peer=78479c35836a7347 type=headers   from=749092
DEBUG[03-03|14:30:16.702] Fetching batch of headers                id=78479c35836a7347 conn=staticdial count=192 fromnum=749092 skip=0   reverse=false
TRACE[03-03|14:30:16.887] Peer throughput measurements updated     peer=78479c35836a7347 hps=103.634  bps=0.000 rps=0.000 sps=0.000 miss=0 rtt=7.86007616s
TRACE[03-03|14:30:16.887] Delivered new batch of data              peer=78479c35836a7347 type=headers   count=192
TRACE[03-03|14:30:16.887] Requesting new batch of data             peer=78479c35836a7347 type=headers   from=749284
DEBUG[03-03|14:30:16.887] Fetching batch of headers                id=78479c35836a7347 conn=staticdial count=192 fromnum=749284 skip=0   reverse=false
TRACE[03-03|14:30:17.074] Peer throughput measurements updated     peer=78479c35836a7347 hps=196.300  bps=0.000 rps=0.000 sps=0.000 miss=0 rtt=7.092703973s
TRACE[03-03|14:30:17.074] Delivered new batch of data              peer=78479c35836a7347 type=headers   count=192
TRACE[03-03|14:30:17.074] Requesting new batch of data             peer=78479c35836a7347 type=headers   from=749476
DEBUG[03-03|14:30:17.074] Fetching batch of headers                id=78479c35836a7347 conn=staticdial count=192 fromnum=749476 skip=0   reverse=false
TRACE[03-03|14:30:17.254] Peer throughput measurements updated     peer=78479c35836a7347 hps=283.220  bps=0.000 rps=0.000 sps=0.000 miss=0 rtt=6.401453225s
TRACE[03-03|14:30:17.254] Delivered new batch of data              peer=78479c35836a7347 type=headers   count=192
TRACE[03-03|14:30:17.254] Requesting new batch of data             peer=78479c35836a7347 type=headers   from=749668
DEBUG[03-03|14:30:17.254] Fetching batch of headers                id=78479c35836a7347 conn=staticdial count=192 fromnum=749668 skip=0   reverse=false
TRACE[03-03|14:30:17.435] Peer throughput measurements updated     peer=78479c35836a7347 hps=360.912  bps=0.000 rps=0.000 sps=0.000 miss=0 rtt=5.7794187s
TRACE[03-03|14:30:17.435] Delivered new batch of data              peer=78479c35836a7347 type=headers   count=192
TRACE[03-03|14:30:17.435] Requesting new batch of data             peer=78479c35836a7347 type=headers   from=749860
DEBUG[03-03|14:30:17.435] Fetching batch of headers                id=78479c35836a7347 conn=staticdial count=192 fromnum=749860 skip=0   reverse=false
TRACE[03-03|14:30:17.620] Peer throughput measurements updated     peer=78479c35836a7347 hps=429.072  bps=0.000 rps=0.000 sps=0.000 miss=0 rtt=5.219893839s
TRACE[03-03|14:30:17.620] Delivered new batch of data              peer=78479c35836a7347 type=headers   count=192
TRACE[03-03|14:30:17.620] Requesting new batch of data             peer=78479c35836a7347 type=headers   from=750052
DEBUG[03-03|14:30:17.620] Fetching batch of headers                id=78479c35836a7347 conn=staticdial count=192 fromnum=750052 skip=0   reverse=false
TRACE[03-03|14:30:17.798] Peer throughput measurements updated     peer=78479c35836a7347 hps=493.814  bps=0.000 rps=0.000 sps=0.000 miss=0 rtt=4.715740224s
TRACE[03-03|14:30:17.798] Delivered new batch of data              peer=78479c35836a7347 type=headers   count=192
TRACE[03-03|14:30:17.798] Requesting new batch of data             peer=78479c35836a7347 type=headers   from=750244
DEBUG[03-03|14:30:17.798] Fetching batch of headers                id=78479c35836a7347 conn=staticdial count=192 fromnum=750244 skip=0   reverse=false
TRACE[03-03|14:30:17.981] Peer throughput measurements updated     peer=78479c35836a7347 hps=549.306  bps=0.000 rps=0.000 sps=0.000 miss=0 rtt=4.262474087s
TRACE[03-03|14:30:17.981] Delivered new batch of data              peer=78479c35836a7347 type=headers   count=192
TRACE[03-03|14:30:17.981] Requesting new batch of data             peer=78479c35836a7347 type=headers   from=750436
DEBUG[03-03|14:30:17.981] Fetching batch of headers                id=78479c35836a7347 conn=staticdial count=192 fromnum=750436 skip=0   reverse=false
TRACE[03-03|14:30:18.161] Peer throughput measurements updated     peer=78479c35836a7347 hps=601.435  bps=0.000 rps=0.000 sps=0.000 miss=0 rtt=3.854160607s
TRACE[03-03|14:30:18.161] Delivered new batch of data              peer=78479c35836a7347 type=headers   count=192
TRACE[03-03|14:30:18.161] Requesting new batch of data             peer=78479c35836a7347 type=headers   from=750628
DEBUG[03-03|14:30:18.161] Fetching batch of headers                id=78479c35836a7347 conn=staticdial count=192 fromnum=750628 skip=0   reverse=false
TRACE[03-03|14:30:18.342] Peer throughput measurements updated     peer=78479c35836a7347 hps=647.193  bps=0.000 rps=0.000 sps=0.000 miss=0 rtt=3.486874518s
TRACE[03-03|14:30:18.342] Delivered new batch of data              peer=78479c35836a7347 type=headers   count=192
TRACE[03-03|14:30:18.342] Requesting new batch of data             peer=78479c35836a7347 type=headers   from=750820
DEBUG[03-03|14:30:18.342] Fetching batch of headers                id=78479c35836a7347 conn=staticdial count=192 fromnum=750820 skip=0   reverse=false
TRACE[03-03|14:30:18.523] Peer throughput measurements updated     peer=78479c35836a7347 hps=688.846  bps=0.000 rps=0.000 sps=0.000 miss=0 rtt=3.156236937s
TRACE[03-03|14:30:18.523] Delivered new batch of data              peer=78479c35836a7347 type=headers   count=192
TRACE[03-03|14:30:18.523] Requesting new batch of data             peer=78479c35836a7347 type=headers   from=751012
DEBUG[03-03|14:30:18.523] Fetching batch of headers                id=78479c35836a7347 conn=staticdial count=192 fromnum=751012 skip=0   reverse=false
TRACE[03-03|14:30:18.699] Peer throughput measurements updated     peer=78479c35836a7347 hps=728.734  bps=0.000 rps=0.000 sps=0.000 miss=0 rtt=2.858264765s
TRACE[03-03|14:30:18.699] Delivered new batch of data              peer=78479c35836a7347 type=headers   count=192
TRACE[03-03|14:30:18.699] Requesting new batch of data             peer=78479c35836a7347 type=headers   from=751204
DEBUG[03-03|14:30:18.699] Fetching batch of headers                id=78479c35836a7347 conn=staticdial count=192 fromnum=751204 skip=0   reverse=false
TRACE[03-03|14:30:18.877] Peer throughput measurements updated     peer=78479c35836a7347 hps=763.851  bps=0.000 rps=0.000 sps=0.000 miss=0 rtt=2.590217641s
TRACE[03-03|14:30:18.877] Delivered new batch of data              peer=78479c35836a7347 type=headers   count=192
TRACE[03-03|14:30:18.877] Requesting new batch of data             peer=78479c35836a7347 type=headers   from=751396
DEBUG[03-03|14:30:18.877] Fetching batch of headers                id=78479c35836a7347 conn=staticdial count=192 fromnum=751396 skip=0   reverse=false
TRACE[03-03|14:30:19.059] Peer throughput measurements updated     peer=78479c35836a7347 hps=793.080  bps=0.000 rps=0.000 sps=0.000 miss=0 rtt=2.349375261s
TRACE[03-03|14:30:19.059] Delivered new batch of data              peer=78479c35836a7347 type=headers   count=192
TRACE[03-03|14:30:19.059] Requesting new batch of data             peer=78479c35836a7347 type=headers   from=751588
DEBUG[03-03|14:30:19.059] Fetching batch of headers                id=78479c35836a7347 conn=staticdial count=192 fromnum=751588 skip=0   reverse=false
TRACE[03-03|14:30:19.239] Peer throughput measurements updated     peer=78479c35836a7347 hps=820.617  bps=0.000 rps=0.000 sps=0.000 miss=0 rtt=2.132407633s
TRACE[03-03|14:30:19.239] Delivered new batch of data              peer=78479c35836a7347 type=headers   count=192
TRACE[03-03|14:30:19.239] Requesting new batch of data             peer=78479c35836a7347 type=headers   from=751780
DEBUG[03-03|14:30:19.239] Fetching batch of headers                id=78479c35836a7347 conn=staticdial count=192 fromnum=751780 skip=0   reverse=false
DEBUG[03-03|14:30:19.401] Recalculated downloader QoS values       rtt=14.59668703s  confidence=1.000 ttl=43.79006109s
TRACE[03-03|14:30:19.415] Peer throughput measurements updated     peer=78479c35836a7347 hps=847.553  bps=0.000 rps=0.000 sps=0.000 miss=0 rtt=1.936781956s
TRACE[03-03|14:30:19.415] Delivered new batch of data              peer=78479c35836a7347 type=headers   count=192
TRACE[03-03|14:30:19.415] Requesting new batch of data             peer=78479c35836a7347 type=headers   from=751972
DEBUG[03-03|14:30:19.415] Fetching batch of headers                id=78479c35836a7347 conn=staticdial count=192 fromnum=751972 skip=0   reverse=false
TRACE[03-03|14:30:19.596] Peer throughput measurements updated     peer=78479c35836a7347 hps=869.270  bps=0.000 rps=0.000 sps=0.000 miss=0 rtt=1.761136601s
TRACE[03-03|14:30:19.596] Delivered new batch of data              peer=78479c35836a7347 type=headers   count=192
TRACE[03-03|14:30:19.596] Requesting new batch of data             peer=78479c35836a7347 type=headers   from=752164
DEBUG[03-03|14:30:19.596] Fetching batch of headers                id=78479c35836a7347 conn=staticdial count=192 fromnum=752164 skip=0   reverse=false
TRACE[03-03|14:30:19.776] Peer throughput measurements updated     peer=78479c35836a7347 hps=888.608  bps=0.000 rps=0.000 sps=0.000 miss=0 rtt=1.603090942s
TRACE[03-03|14:30:19.776] Delivered new batch of data              peer=78479c35836a7347 type=headers   count=192
TRACE[03-03|14:30:19.776] Requesting new batch of data             peer=78479c35836a7347 type=headers   from=752356
DEBUG[03-03|14:30:19.776] Fetching batch of headers                id=78479c35836a7347 conn=staticdial count=192 fromnum=752356 skip=0   reverse=false
TRACE[03-03|14:30:19.954] Peer throughput measurements updated     peer=78479c35836a7347 hps=907.581  bps=0.000 rps=0.000 sps=0.000 miss=0 rtt=1.46058703s
TRACE[03-03|14:30:19.954] Delivered new batch of data              peer=78479c35836a7347 type=headers   count=192
TRACE[03-03|14:30:19.955] Requesting new batch of data             peer=78479c35836a7347 type=headers   from=752548
DEBUG[03-03|14:30:19.955] Fetching batch of headers                id=78479c35836a7347 conn=staticdial count=192 fromnum=752548 skip=0   reverse=false
TRACE[03-03|14:30:20.132] Peer throughput measurements updated     peer=78479c35836a7347 hps=925.062  bps=0.000 rps=0.000 sps=0.000 miss=0 rtt=1.332266846s
TRACE[03-03|14:30:20.132] Delivered new batch of data              peer=78479c35836a7347 type=headers   count=192
TRACE[03-03|14:30:20.132] Requesting new batch of data             peer=78479c35836a7347 type=headers   from=752740
DEBUG[03-03|14:30:20.132] Fetching batch of headers                id=78479c35836a7347 conn=staticdial count=192 fromnum=752740 skip=0   reverse=false
TRACE[03-03|14:30:20.322] Peer throughput measurements updated     peer=78479c35836a7347 hps=933.622  bps=0.000 rps=0.000 sps=0.000 miss=0 rtt=1.218037628s
TRACE[03-03|14:30:20.322] Delivered new batch of data              peer=78479c35836a7347 type=headers   count=192
TRACE[03-03|14:30:20.322] Requesting new batch of data             peer=78479c35836a7347 type=headers   from=752932
DEBUG[03-03|14:30:20.322] Fetching batch of headers                id=78479c35836a7347 conn=staticdial count=192 fromnum=752932 skip=0   reverse=false
TRACE[03-03|14:30:20.512] Peer throughput measurements updated     peer=78479c35836a7347 hps=941.595  bps=0.000 rps=0.000 sps=0.000 miss=0 rtt=1.115180874s
TRACE[03-03|14:30:20.512] Delivered new batch of data              peer=78479c35836a7347 type=headers   count=192
TRACE[03-03|14:30:20.512] Requesting new batch of data             peer=78479c35836a7347 type=headers   from=753124
DEBUG[03-03|14:30:20.512] Fetching batch of headers                id=78479c35836a7347 conn=staticdial count=192 fromnum=753124 skip=0   reverse=false
TRACE[03-03|14:30:20.691] Peer throughput measurements updated     peer=78479c35836a7347 hps=954.590  bps=0.000 rps=0.000 sps=0.000 miss=0 rtt=1.021580892s
TRACE[03-03|14:30:20.691] Delivered new batch of data              peer=78479c35836a7347 type=headers   count=192
TRACE[03-03|14:30:20.691] Requesting new batch of data             peer=78479c35836a7347 type=headers   from=753316
DEBUG[03-03|14:30:20.691] Fetching batch of headers                id=78479c35836a7347 conn=staticdial count=192 fromnum=753316 skip=0   reverse=false
DEBUG[03-03|14:30:20.833] Ethereum peer connected                  id=c942e4c950050815 conn=dyndial    name=Pirl/v1.8.2-v5-masternode-content-hulk-fd4b5d67/linux-amd64/go1.10
TRACE[03-03|14:30:20.870] Peer throughput measurements updated     peer=78479c35836a7347 hps=966.207  bps=0.000 rps=0.000 sps=0.000 miss=0 rtt=937.35398ms
TRACE[03-03|14:30:20.870] Delivered new batch of data              peer=78479c35836a7347 type=headers   count=192
TRACE[03-03|14:30:20.870] Requesting new batch of data             peer=78479c35836a7347 type=headers   from=753508
DEBUG[03-03|14:30:20.870] Fetching batch of headers                id=78479c35836a7347 conn=staticdial count=192 fromnum=753508 skip=0   reverse=false
DEBUG[03-03|14:30:20.965] Ethereum handshake failed                id=c942e4c950050815 conn=dyndial    err=EOF
DEBUG[03-03|14:30:21.017] Ethereum peer connected                  id=fa6f317f47d6b73b conn=dyndial    name=gwhale/v1.6.9-stable-2cd1fe07/linux-amd64/go1.10.1
TRACE[03-03|14:30:21.055] Peer throughput measurements updated     peer=78479c35836a7347 hps=973.461  bps=0.000 rps=0.000 sps=0.000 miss=0 rtt=862.102435ms
TRACE[03-03|14:30:21.055] Delivered new batch of data              peer=78479c35836a7347 type=headers   count=192
TRACE[03-03|14:30:21.055] Requesting new batch of data             peer=78479c35836a7347 type=headers   from=753700
DEBUG[03-03|14:30:21.055] Fetching batch of headers                id=78479c35836a7347 conn=staticdial count=192 fromnum=753700 skip=0   reverse=false
DEBUG[03-03|14:30:21.103] Ethereum handshake failed                id=fa6f317f47d6b73b conn=dyndial    err="Genesis block mismatch - 331ebb4480a55f03 (!= 34be4c6eecd55a5c)"
TRACE[03-03|14:30:21.238] Peer throughput measurements updated     peer=78479c35836a7347 hps=980.914  bps=0.000 rps=0.000 sps=0.000 miss=0 rtt=794.212823ms
TRACE[03-03|14:30:21.238] Delivered new batch of data              peer=78479c35836a7347 type=headers   count=192
TRACE[03-03|14:30:21.239] Requesting new batch of data             peer=78479c35836a7347 type=headers   from=753892
DEBUG[03-03|14:30:21.239] Fetching batch of headers                id=78479c35836a7347 conn=staticdial count=192 fromnum=753892 skip=0   reverse=false
DEBUG[03-03|14:30:21.271] Ethereum peer connected                  id=b27284daaed935fc conn=dyndial    name=Parity-Ethereum/v2.1.8-stable-3eae1d3-20181130/x86_64-linux-gnu/rustc1.30.1
DEBUG[03-03|14:30:21.368] Ethereum handshake failed                id=b27284daaed935fc conn=dyndial    err="Genesis block mismatch - 586817cd17aa2108 (!= 34be4c6eecd55a5c)"
TRACE[03-03|14:30:21.416] Peer throughput measurements updated     peer=78479c35836a7347 hps=991.090  bps=0.000 rps=0.000 sps=0.000 miss=0 rtt=732.525532ms
TRACE[03-03|14:30:21.416] Delivered new batch of data              peer=78479c35836a7347 type=headers   count=192
TRACE[03-03|14:30:21.416] Requesting new batch of data             peer=78479c35836a7347 type=headers   from=754084
DEBUG[03-03|14:30:21.416] Fetching batch of headers                id=78479c35836a7347 conn=staticdial count=192 fromnum=754084 skip=0   reverse=false
TRACE[03-03|14:30:21.598] Peer throughput measurements updated     peer=78479c35836a7347 hps=997.680  bps=0.000 rps=0.000 sps=0.000 miss=0 rtt=677.437792ms
TRACE[03-03|14:30:21.598] Delivered new batch of data              peer=78479c35836a7347 type=headers   count=192
TRACE[03-03|14:30:21.598] Requesting new batch of data             peer=78479c35836a7347 type=headers   from=754276
DEBUG[03-03|14:30:21.598] Fetching batch of headers                id=78479c35836a7347 conn=staticdial count=192 fromnum=754276 skip=0   reverse=false
TRACE[03-03|14:30:21.775] Peer throughput measurements updated     peer=78479c35836a7347 hps=1006.233 bps=0.000 rps=0.000 sps=0.000 miss=0 rtt=627.419092ms
TRACE[03-03|14:30:21.775] Delivered new batch of data              peer=78479c35836a7347 type=headers   count=192
TRACE[03-03|14:30:21.775] Requesting new batch of data             peer=78479c35836a7347 type=headers   from=754468
DEBUG[03-03|14:30:21.775] Fetching batch of headers                id=78479c35836a7347 conn=staticdial count=192 fromnum=754468 skip=0   reverse=false
TRACE[03-03|14:30:21.956] Peer throughput measurements updated     peer=78479c35836a7347 hps=1011.881 bps=0.000 rps=0.000 sps=0.000 miss=0 rtt=582.744155ms
TRACE[03-03|14:30:21.956] Delivered new batch of data              peer=78479c35836a7347 type=headers   count=192
TRACE[03-03|14:30:21.956] Requesting new batch of data             peer=78479c35836a7347 type=headers   from=754660
DEBUG[03-03|14:30:21.956] Fetching batch of headers                id=78479c35836a7347 conn=staticdial count=192 fromnum=754660 skip=0   reverse=false
TRACE[03-03|14:30:22.138] Peer throughput measurements updated     peer=78479c35836a7347 hps=1016.040 bps=0.000 rps=0.000 sps=0.000 miss=0 rtt=542.695209ms
TRACE[03-03|14:30:22.138] Delivered new batch of data              peer=78479c35836a7347 type=headers   count=192
TRACE[03-03|14:30:22.138] Requesting new batch of data             peer=78479c35836a7347 type=headers   from=754852
DEBUG[03-03|14:30:22.138] Fetching batch of headers                id=78479c35836a7347 conn=staticdial count=192 fromnum=754852 skip=0   reverse=false
TRACE[03-03|14:30:22.320] Peer throughput measurements updated     peer=78479c35836a7347 hps=1020.103 bps=0.000 rps=0.000 sps=0.000 miss=0 rtt=506.595929ms
TRACE[03-03|14:30:22.320] Delivered new batch of data              peer=78479c35836a7347 type=headers   count=192
TRACE[03-03|14:30:22.320] Requesting new batch of data             peer=78479c35836a7347 type=headers   from=755044
DEBUG[03-03|14:30:22.320] Fetching batch of headers                id=78479c35836a7347 conn=staticdial count=192 fromnum=755044 skip=0   reverse=false
DEBUG[03-03|14:30:22.511] Ethereum peer connected                  id=773895eb76192e0d conn=inbound    name=Parity-Ethereum/v2.2.10-stable-7b1d3e180-20190213/x86_64-linux-musl/rustc1.31.1
TRACE[03-03|14:30:22.514] Peer throughput measurements updated     peer=78479c35836a7347 hps=1016.874 bps=0.000 rps=0.000 sps=0.000 miss=0 rtt=475.373222ms
TRACE[03-03|14:30:22.514] Delivered new batch of data              peer=78479c35836a7347 type=headers   count=192
TRACE[03-03|14:30:22.514] Requesting new batch of data             peer=78479c35836a7347 type=headers   from=755236
DEBUG[03-03|14:30:22.514] Fetching batch of headers                id=78479c35836a7347 conn=staticdial count=192 fromnum=755236 skip=0   reverse=false
DEBUG[03-03|14:30:22.633] Ethereum handshake failed                id=773895eb76192e0d conn=inbound    err="Genesis block mismatch - d4e56740f876aef8 (!= 34be4c6eecd55a5c)"
TRACE[03-03|14:30:22.702] Peer throughput measurements updated     peer=78479c35836a7347 hps=1017.812 bps=0.000 rps=0.000 sps=0.000 miss=0 rtt=446.544719ms
TRACE[03-03|14:30:22.702] Delivered new batch of data              peer=78479c35836a7347 type=headers   count=192
TRACE[03-03|14:30:22.702] Requesting new batch of data             peer=78479c35836a7347 type=headers   from=755428
DEBUG[03-03|14:30:22.702] Fetching batch of headers                id=78479c35836a7347 conn=staticdial count=192 fromnum=755428 skip=0   reverse=false
TRACE[03-03|14:30:22.899] Peer throughput measurements updated     peer=78479c35836a7347 hps=1013.545 bps=0.000 rps=0.000 sps=0.000 miss=0 rtt=421.579578ms
TRACE[03-03|14:30:22.899] Delivered new batch of data              peer=78479c35836a7347 type=headers   count=192
TRACE[03-03|14:30:22.899] Requesting new batch of data             peer=78479c35836a7347 type=headers   from=755620
DEBUG[03-03|14:30:22.899] Fetching batch of headers                id=78479c35836a7347 conn=staticdial count=192 fromnum=755620 skip=0   reverse=false
TRACE[03-03|14:30:23.099] Peer throughput measurements updated     peer=78479c35836a7347 hps=1007.845 bps=0.000 rps=0.000 sps=0.000 miss=0 rtt=399.493876ms
TRACE[03-03|14:30:23.099] Delivered new batch of data              peer=78479c35836a7347 type=headers   count=192
TRACE[03-03|14:30:23.099] Requesting new batch of data             peer=78479c35836a7347 type=headers   from=755812
DEBUG[03-03|14:30:23.099] Fetching batch of headers                id=78479c35836a7347 conn=staticdial count=192 fromnum=755812 skip=0   reverse=false
DEBUG[03-03|14:30:23.222] Ethereum peer connected                  id=e628691d970033f2 conn=dyndial    name=Geth/v1.9.0-unstable-9d5e10f5/linux-amd64/go1.11.5
WARN [03-03|14:30:23.296] Header broke chain ancestry              peer=78479c35836a7347 number=755837 hash=f42b94…e858e5
TRACE[03-03|14:30:23.296] Skeleton filling not accepted            peer=78479c35836a7347 from=755812
TRACE[03-03|14:30:23.297] Failed to deliver retrieved data         peer=78479c35836a7347 type=headers   err="delivery not accepted"
DEBUG[03-03|14:30:23.297] Skeleton fill terminated                 err="no peers available or all tried for download"
DEBUG[03-03|14:30:23.297] Skeleton chain invalid                   peer=78479c35836a7347 err="no peers available or all tried for download"
DEBUG[03-03|14:30:23.297] Header download terminated               peer=78479c35836a7347
DEBUG[03-03|14:30:23.297] Transaction receipt download terminated  err="receipt download canceled (requested)"
DEBUG[03-03|14:30:23.297] Block body download terminated           err="block body download canceled (requested)"
DEBUG[03-03|14:30:23.297] Synchronisation terminated               elapsed=9.009811741s
WARN [03-03|14:30:23.297] Synchronisation failed, dropping peer    peer=78479c35836a7347 err="retrieved hash chain is invalid"
DEBUG[03-03|14:30:23.297] Removing Ethereum peer                   peer=78479c35836a7347
TRACE[03-03|14:30:23.297] Unregistering sync peer                  peer=78479c35836a7347
DEBUG[03-03|14:30:23.297] Ethereum message handling failed         id=78479c35836a7347 conn=staticdial err=EOF
DEBUG[03-03|14:30:23.519] Ethereum handshake failed                id=e628691d970033f2 conn=dyndial    err=EOF
DEBUG[03-03|14:30:24.144] Ethereum peer connected                  id=52fc4fc288992e28 conn=inbound    name=Parity-Ethereum/v2.2.10-stable-7b1d3e1-20190213/x86_64-linux-gnu/rustc1.32.0
DEBUG[03-03|14:30:24.298] Ethereum peer connected                  id=69ccacb22a97e792 conn=inbound    name=Gubiq/v1.5.12-flux-43a56777/linux/go1.8.1
DEBUG[03-03|14:30:24.298] Ethereum handshake failed                id=69ccacb22a97e792 conn=inbound    err="Genesis block mismatch - 406f1b7dd39fca54 (!= 34be4c6eecd55a5c)"
DEBUG[03-03|14:30:24.411] Ethereum handshake failed                id=52fc4fc288992e28 conn=inbound    err="Genesis block mismatch - d4e56740f876aef8 (!= 34be4c6eecd55a5c)"
DEBUG[03-03|14:30:24.986] Ethereum peer connected                  id=f5282c7b8bda83f3 conn=inbound    name=Geth/DrJimmy/v1.8.22-stable-7fa3509e/linux-amd64/go1.11.5
DEBUG[03-03|14:30:24.996] Ethereum handshake failed                id=f5282c7b8bda83f3 conn=inbound    err="Genesis block mismatch - d4e56740f876aef8 (!= 34be4c6eecd55a5c)"
DEBUG[03-03|14:30:27.324] Ethereum peer connected                  id=f586ca029c2de399 conn=dyndial    name=Geth/v0.1.1-akroma-5fa3ee8c/linux-amd64/go1.10.1
DEBUG[03-03|14:30:27.587] Ethereum handshake failed                id=f586ca029c2de399 conn=dyndial    err="Genesis block mismatch - 679ee3d5213ddab6 (!= 34be4c6eecd55a5c)"
DEBUG[03-03|14:30:27.987] Ethereum peer connected                  id=e09333054dbc03ec conn=dyndial    name=Geth/v1.9.0-unstable-c1c43011/darwin-amd64/go1.11.1
DEBUG[03-03|14:30:28.285] Ethereum handshake failed                id=e09333054dbc03ec conn=dyndial    err=EOF
DEBUG[03-03|14:30:29.575] Ethereum peer connected                  id=ab62dd7df5863a5f conn=inbound    name=Geth/v1.7.0-unstable-8ba6534b/linux-amd64/go1.7.6
DEBUG[03-03|14:30:29.575] Ethereum handshake failed                id=ab62dd7df5863a5f conn=inbound    err="Genesis block mismatch - 614556b2e69440f1 (!= 34be4c6eecd55a5c)"
DEBUG[03-03|14:30:30.355] Ethereum peer connected                  id=c7262f618d5de678 conn=inbound    name=Geth/v1.8.13-stable-225171a4/linux-amd64/go1.10.3
DEBUG[03-03|14:30:30.355] Ethereum handshake failed                id=c7262f618d5de678 conn=inbound    err="Genesis block mismatch - d4e56740f876aef8 (!= 34be4c6eecd55a5c)"

**Comment by cyberfab007** [comment]
turn up your verbosity like this and post debug.vmodule("eth/*=6")

**Comment by cyberfab007** [comment]
DEBUG[03-03|14:30:28.285] Ethereum handshake failed id=e09333054dbc03ec conn=dyndial err=EOF
DEBUG[03-03|14:30:29.575] Ethereum peer connected id=ab62dd7df5863a5f conn=inbound name=Geth/v1.7.0-unstable-8ba6534b/linux-amd64/go1.7.6
DEBUG[03-03|14:30:29.575] Ethereum handshake failed id=ab62dd7df5863a5f conn=inbound err="Genesis block mismatch - 614556b2e69440f1 (!= 34be4c6eecd55a5c)"
DEBUG[03-03|14:30:30.355] Ethereum peer connected id=c7262f618d5de678 conn=inbound name=Geth/v1.8.13-stable-225171a4/linux-amd64/go1.10.3
DEBUG[03-03|14:30:30.355] Ethereum handshake failed id=c7262f618d5de678 conn=inbound err="Genesis block mismatch - d4e56740f876aef8 (!= 34be4c6eecd55a5c)"

**Comment by cyberfab007** [comment]
I checked genesis keys and files they are exact

**Comment by philipempl** [comment]
Hi there,
do you have found any solution? Im running into the same error for weeks now. The only thing that helped was a reset of the node, but this includes deleting the whole database and creating a new account....
Hope that anyone can help me out1
Thanks in advance

Best regards,
Philip

**Comment by Ogulcan-Ozdemir** [comment]
Hello I'm facing same issue. I run private local network with Proof of Authroity with 2 node.
Sealer node works fine but transcational node give same error continusly.

**Comment by Ogulcan-Ozdemir** [comment]
This bug solved with update between 1.8.22 and 1.9.1 stable  version I dont know exactly which version. But posterior node evantualy sync with other node and accept transcation normally

**Comment by rrodriguezreche** [comment]
Not solved at

```
Geth
Version: 1.9.8-stable
Git Commit: d62e9b285777c036c108b89fac0c78f7855ba314
Git Commit Date: 20191126
Architecture: amd64
Protocol Versions: [64 63]
```

**Comment by karalabe** [comment]
This is probably the sympom of https://github.com/ethereum/go-ethereum/issues/20238

**Comment by garyng2000** [comment]
still seeing this 1.9.19 running on Windows(POW private node), 1.9.20 on Linux(sync from Windows machine). I tried to restarted from scratch(i.e. remove the whole directory) a few times still the same(and tried full/fast). Once it reaches the end(i.e. kind of synced), new blocks no longer sync and keep on seeing this error.

**Comment by holiman** [comment]
@garyng2000 you're giving too little details. Based on the few nuggets of info provided, some example errors can be

- You're on a private chain, but your private chain uses an existing network id, so you keep finding peers that are on different chains, 
- You are having connectivity problems between your peers, maybe they are on the same internal NAT network but all punch through NAT and report their own IPs as the external IP, causing routing problems. 
- You are doing a fast-sync, and when you say  "kind of synced" it's actually still fetching state and occasionally moving the pivot block

If you are having issues, please open a new ticket and provide the full details, start commands, logs, node info etc. It's better to add a reference from the new ticket to the old (closed) one, rather than to add a comment on the old (closed) ticket.
