### ISSUE TITLE
geth repeatedly crashes with SIGSEGV

### ISSUE THREAD

**Issue by m0ar** [ethereum/go-ethereum#20190]
#### System information

Geth version: 1.9.6-stable
OS & Version: Linux 4.19.66-v7l+
Go: go1.13 linux/arm

#### Expected behaviour
Geth service syncs the chain.

#### Actual behaviour
Geth crashes repeatedly when service is started.

#### Steps to reproduce the behaviour
I'm not sure why this happens, but it did not appear during fast sync. When the node was (or almost) caught up with the chain, it started to crash repeatedly. Tried rebuilding geth today with the latest release (1.9.6), but crashes persist.

#### Backtrace

````
Oct 21 11:33:04 evl-geth systemd[1]: Started Geth Node.
Oct 21 11:33:04 evl-geth geth[5793]: INFO [10-21|11:33:04.557] Maximum peer count                       ETH=50 LES=0 total=50
Oct 21 11:33:04 evl-geth geth[5793]: INFO [10-21|11:33:04.558] Smartcard socket not found, disabling    err="stat /run/pcscd/pcscd.comm: no such file or directory"
Oct 21 11:33:04 evl-geth geth[5793]: INFO [10-21|11:33:04.562] Starting peer-to-peer node               instance=Geth/v1.9.6-stable-bd059680/linux-arm/go1.13
Oct 21 11:33:04 evl-geth geth[5793]: INFO [10-21|11:33:04.563] Allocated trie memory caches             clean=64.00MiB dirty=64.00MiB
Oct 21 11:33:04 evl-geth geth[5793]: INFO [10-21|11:33:04.563] Allocated cache and file handles         database=/mnt/ssd/ethereum/geth/chaindata cache=128.00MiB handles=262144
Oct 21 11:33:06 evl-geth geth[5793]: INFO [10-21|11:33:06.000] Opened ancient database                  database=/mnt/ssd/ethereum/geth/chaindata/ancient
Oct 21 11:33:06 evl-geth geth[5793]: INFO [10-21|11:33:06.008] Initialised chain configuration          config="{ChainID: 1 Homestead: 1150000 DAO: 1920000 DAOSupport: true EIP150: 2463000 EIP155: 2675000 EIP158: 2675000 Byzantium: 4370000 Constantinople: 7280000 Petersburg: 7280000 Istanbul: <nil> Engine: ethash}"
Oct 21 11:33:06 evl-geth geth[5793]: INFO [10-21|11:33:06.008] Disk storage enabled for ethash caches   dir=/mnt/ssd/ethereum/geth/ethash count=3
Oct 21 11:33:06 evl-geth geth[5793]: INFO [10-21|11:33:06.008] Disk storage enabled for ethash DAGs     dir=/home/pi/.ethash              count=2
Oct 21 11:33:06 evl-geth geth[5793]: INFO [10-21|11:33:06.010] Initialising Ethereum protocol           versions=[63] network=1 dbversion=7
Oct 21 11:33:06 evl-geth geth[5793]: INFO [10-21|11:33:06.062] Loaded most recent local header          number=8714751 hash=398925…4639c7 td=12312815174212912772480 age=1w3d19h
Oct 21 11:33:06 evl-geth geth[5793]: INFO [10-21|11:33:06.062] Loaded most recent local full block      number=8714666 hash=6a936b…e922eb td=12312604899411814897379 age=1w3d19h
Oct 21 11:33:06 evl-geth geth[5793]: INFO [10-21|11:33:06.062] Loaded most recent local fast block      number=8714751 hash=398925…4639c7 td=12312815174212912772480 age=1w3d19h
Oct 21 11:33:06 evl-geth geth[5793]: INFO [10-21|11:33:06.064] Loaded local transaction journal         transactions=0 dropped=0
Oct 21 11:33:06 evl-geth geth[5793]: INFO [10-21|11:33:06.065] Regenerated local transaction journal    transactions=0 accounts=0
Oct 21 11:33:06 evl-geth geth[5793]: WARN [10-21|11:33:06.065] Switch sync mode from fast sync to full sync
Oct 21 11:33:06 evl-geth geth[5793]: INFO [10-21|11:33:06.159] New local node record                    seq=890 id=b0ae5886b9284f06 ip=127.0.0.1 udp=30303 tcp=30303
Oct 21 11:33:06 evl-geth geth[5793]: INFO [10-21|11:33:06.162] Started P2P networking                   self=enode://e64123ecdd615fa43ba43ff014f2802afd5b39c70d2b9b48d2a8358063bfecd171dadbf042fd8c08239257cfbc34c6b3fbe5f79021a395776e8ee3ab4f0bbc57@127.0.0.1:30303
Oct 21 11:33:06 evl-geth geth[5793]: INFO [10-21|11:33:06.168] IPC endpoint opened                      url=/mnt/ssd/ethereum/geth.ipc
Oct 21 11:33:16 evl-geth geth[5793]: INFO [10-21|11:33:16.162] Block synchronisation started
Oct 21 11:33:17 evl-geth geth[5793]: panic: runtime error: invalid memory address or nil pointer dereference
Oct 21 11:33:17 evl-geth geth[5793]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x1b8 pc=0x63d828]
Oct 21 11:33:17 evl-geth geth[5793]: goroutine 263 [running]:
Oct 21 11:33:17 evl-geth geth[5793]: github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).findAncestor(0x24bac80, 0x2672480, 0x4a5d440, 0x0, 0x0, 0xa, 0xa)
Oct 21 11:33:17 evl-geth geth[5793]: #011/home/pi/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:877 +0x1500
Oct 21 11:33:17 evl-geth geth[5793]: github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).syncWithPeer(0x24bac80, 0x2672480, 0x5ca3af9d, 0x3c227bfb, 0xc13762f3, 0x5704518b, 0x7de03df6, 0xf0182a20, 0xc22975cd, 0x400256e9, ...)
Oct 21 11:33:17 evl-geth geth[5793]: #011/home/pi/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:443 +0x2a0
Oct 21 11:33:17 evl-geth geth[5793]: github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).synchronise(0x24bac80, 0x86fe140, 0x10, 0x5ca3af9d, 0x3c227bfb, 0xc13762f3, 0x5704518b, 0x7de03df6, 0xf0182a20, 0xc22975cd, ...)
Oct 21 11:33:17 evl-geth geth[5793]: #011/home/pi/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:411 +0x338
Oct 21 11:33:17 evl-geth geth[5793]: github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).Synchronise(0x24bac80, 0x86fe140, 0x10, 0x5ca3af9d, 0x3c227bfb, 0xc13762f3, 0x5704518b, 0x7de03df6, 0xf0182a20, 0xc22975cd, ...)
Oct 21 11:33:17 evl-geth geth[5793]: #011/home/pi/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:323 +0x5c
Oct 21 11:33:17 evl-geth geth[5793]: github.com/ethereum/go-ethereum/eth.(*ProtocolManager).synchronise(0x49a81b0, 0x8631500)
Oct 21 11:33:17 evl-geth geth[5793]: #011/home/pi/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/sync.go:190 +0x1b0
Oct 21 11:33:17 evl-geth geth[5793]: created by github.com/ethereum/go-ethereum/eth.(*ProtocolManager).syncer
Oct 21 11:33:17 evl-geth geth[5793]: #011/home/pi/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/sync.go:155 +0x17c
Oct 21 11:33:17 evl-geth systemd[1]: geth.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Oct 21 11:33:17 evl-geth systemd[1]: geth.service: Failed with result 'exit-code'.
````

**Comment by holiman** [comment]
Fast sync block is `8714751`, full sync block is `8714666`. Then it switches to full-sync mode, and tries to import blocks one by one...

Could you try it with some more detailed logging in place?

**Comment by m0ar** [comment]
@holiman Absolutely, here is the output from `--verbosity 5`: https://gist.github.com/m0ar/9b13cd900b324152b41abb339b291eb9

**Comment by holiman** [comment]
Interesting. It looks like the block body for block `8716041` exists, but the header seems to not be present.

**Comment by holiman** [comment]
> Is there any way I can get through this impasse?

One thing that might work is to use `debug.setHead` at `8714666`.

**Comment by holiman** [comment]
@m0ar the first crash you had -- do you know if that was the exact _same_ crash as this one? I'm thinking that maybe the first crash left the db a bit corrupted, and now you're hitting this because some data is missing in the db. 

Also, what hardware are you running on ? What's the ram size?

**Comment by m0ar** [comment]
@holiman How can I set this before the client crashes? It fails within seconds.

**Comment by m0ar** [comment]
Got it done. It definitely ran for longer, but crashed again:
```
[...]
TRACE[10-23|09:43:56.593] >> PING/v4                               id=87f1a269da09b133 addr=164.15.10.134:1439    err=nil
TRACE[10-23|09:43:56.602] >> FINDNODE/v4                           id=87f2609389c3c75f addr=74.71.193.225:30303   err=nil
TRACE[10-23|09:43:56.683] Filtering headers                        peer=fbecffbe2c173d8a headers=1
DEBUG[10-23|09:43:56.684] Remote head header identified            peer=fbecffbe2c173d8a number=8795682 hash=8952d0…f3c6e0
DEBUG[10-23|09:43:56.684] Looking for common ancestor              peer=fbecffbe2c173d8a local=8714666 remote=8795682
TRACE[10-23|09:43:56.684] Span searching for common ancestor       peer=fbecffbe2c173d8a count=12 from=8795505 skip=15
DEBUG[10-23|09:43:56.684] Fetching batch of headers                id=fbecffbe2c173d8a conn=dyndial         count=12 fromnum=8795505 skip=15 reverse=false
DEBUG[10-23|09:43:56.693] Peer discarded announcement              peer=fbecffbe2c173d8a number=8795684 hash=710e5d…04f5f2 distance=81018
TRACE[10-23|09:43:56.748] >> FINDNODE/v4                           id=dc1e03b53752c6d7 addr=113.52.133.48:30303   err=nil
TRACE[10-23|09:43:56.771] Binary searching for common ancestor     peer=fbecffbe2c173d8a start=8624666 end=8795682
DEBUG[10-23|09:43:56.772] Fetching batch of headers                id=fbecffbe2c173d8a conn=dyndial         count=1  fromnum=8710174 skip=0  reverse=false
TRACE[10-23|09:43:56.936] Filtering headers                        peer=fbecffbe2c173d8a headers=1
DEBUG[10-23|09:43:56.944] Fetching batch of headers                id=fbecffbe2c173d8a conn=dyndial         count=1  fromnum=8752928 skip=0  reverse=false
TRACE[10-23|09:43:56.990] Filtering headers                        peer=fbecffbe2c173d8a headers=1
DEBUG[10-23|09:43:56.991] Fetching batch of headers                id=fbecffbe2c173d8a conn=dyndial         count=1  fromnum=8731551 skip=0  reverse=false
TRACE[10-23|09:43:57.083] >> FINDNODE/v4                           id=dc1d32b41bfa9f2c addr=165.22.28.47:50000    err=nil
TRACE[10-23|09:43:57.083] Filtering headers                        peer=fbecffbe2c173d8a headers=1
DEBUG[10-23|09:43:57.084] Fetching batch of headers                id=fbecffbe2c173d8a conn=dyndial         count=1  fromnum=8720862 skip=0  reverse=false
TRACE[10-23|09:43:57.101] Findnode failed                          id=87f2609389c3c75f failcount=1   err="RPC timeout"
TRACE[10-23|09:43:57.103] >> PING/v4                               id=87f4880a9638d756 addr=94.79.55.28:30000     err=nil
TRACE[10-23|09:43:57.154] Filtering headers                        peer=fbecffbe2c173d8a headers=1
DEBUG[10-23|09:43:57.155] Fetching batch of headers                id=fbecffbe2c173d8a conn=dyndial         count=1  fromnum=8715518 skip=0  reverse=false
TRACE[10-23|09:43:57.234] Filtering headers                        peer=fbecffbe2c173d8a headers=1
DEBUG[10-23|09:43:57.240] Fetching batch of headers                id=fbecffbe2c173d8a conn=dyndial         count=1  fromnum=8718190 skip=0  reverse=false
TRACE[10-23|09:43:57.247] Findnode failed                          id=dc1e03b53752c6d7 failcount=3   err="RPC timeout"
TRACE[10-23|09:43:57.249] >> PING/v4                               id=dc1d079a808feccf addr=91.55.92.55:30303     err=nil
TRACE[10-23|09:43:57.349] Filtering headers                        peer=fbecffbe2c173d8a headers=1
DEBUG[10-23|09:43:57.350] Fetching batch of headers                id=fbecffbe2c173d8a conn=dyndial         count=1  fromnum=8716854 skip=0  reverse=false
TRACE[10-23|09:43:57.397] Filtering headers                        peer=fbecffbe2c173d8a headers=1
DEBUG[10-23|09:43:57.398] Fetching batch of headers                id=fbecffbe2c173d8a conn=dyndial         count=1  fromnum=8716186 skip=0  reverse=false
TRACE[10-23|09:43:57.444] Filtering headers                        peer=fbecffbe2c173d8a headers=1
DEBUG[10-23|09:43:57.445] Fetching batch of headers                id=fbecffbe2c173d8a conn=dyndial         count=1  fromnum=8715852 skip=0  reverse=false
DEBUG[10-23|09:43:57.466] Peer discarded announcement              peer=fbecffbe2c173d8a number=8795684 hash=d9d7fb…bded03 distance=81018
TRACE[10-23|09:43:57.475] >> FINDNODE/v4                           id=87f1d99d692cc00e addr=116.253.203.71:5818   err=nil
TRACE[10-23|09:43:57.481] Filtering headers                        peer=fbecffbe2c173d8a headers=1
DEBUG[10-23|09:43:57.488] Fetching batch of headers                id=fbecffbe2c173d8a conn=dyndial         count=1  fromnum=8716019 skip=0  reverse=false
TRACE[10-23|09:43:57.514] >> FINDNODE/v4                           id=dc1d3faf109a9f5b addr=157.245.93.35:50000   err=nil
TRACE[10-23|09:43:57.541] Filtering headers                        peer=fbecffbe2c173d8a headers=1
DEBUG[10-23|09:43:57.543] Fetching batch of headers                id=fbecffbe2c173d8a conn=dyndial         count=1  fromnum=8716102 skip=0  reverse=false
TRACE[10-23|09:43:57.573] Filtering headers                        peer=fbecffbe2c173d8a headers=1
DEBUG[10-23|09:43:57.575] Fetching batch of headers                id=fbecffbe2c173d8a conn=dyndial         count=1  fromnum=8716060 skip=0  reverse=false
TRACE[10-23|09:43:57.582] Findnode failed                          id=dc1d32b41bfa9f2c failcount=2   err="RPC timeout"
TRACE[10-23|09:43:57.584] >> PING/v4                               id=dc1cc69c6a05eb8f addr=13.230.252.33:30303   err=nil
TRACE[10-23|09:43:57.595] >> FINDNODE/v4                           id=87f1a269da09b133 addr=164.15.10.134:1439    err=nil
TRACE[10-23|09:43:57.661] Filtering headers                        peer=fbecffbe2c173d8a headers=1
DEBUG[10-23|09:43:57.661] Fetching batch of headers                id=fbecffbe2c173d8a conn=dyndial         count=1  fromnum=8716039 skip=0  reverse=false
TRACE[10-23|09:43:57.697] Filtering headers                        peer=fbecffbe2c173d8a headers=1
DEBUG[10-23|09:43:57.700] Fetching batch of headers                id=fbecffbe2c173d8a conn=dyndial         count=1  fromnum=8716049 skip=0  reverse=false
TRACE[10-23|09:43:57.753] Filtering headers                        peer=fbecffbe2c173d8a headers=1
DEBUG[10-23|09:43:57.754] Fetching batch of headers                id=fbecffbe2c173d8a conn=dyndial         count=1  fromnum=8716044 skip=0  reverse=false
TRACE[10-23|09:43:57.787] Filtering headers                        peer=fbecffbe2c173d8a headers=1
DEBUG[10-23|09:43:57.787] Fetching batch of headers                id=fbecffbe2c173d8a conn=dyndial         count=1  fromnum=8716041 skip=0  reverse=false
TRACE[10-23|09:43:57.847] Filtering headers                        peer=fbecffbe2c173d8a headers=1
DEBUG[10-23|09:43:57.851] Synchronisation terminated               elapsed=11.386s
DEBUG[10-23|09:43:57.851] Reset ancient limit to zero 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x1b8 pc=0x63d828]

goroutine 376 [running]:
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).findAncestor(0x24bac80, 0x266c6c0, 0x398b440, 0x0, 0x0, 0xa, 0xa)
	/home/pi/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:877 +0x1500
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).syncWithPeer(0x24bac80, 0x266c6c0, 0xc3d05289, 0x15726f7b, 0x93e43866, 0xc042d0bd, 0x75832ac, 0xc6690d42, 0xd013c950, 0xe0c6f3ee, ...)
	/home/pi/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:443 +0x2a0
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).synchronise(0x24bac80, 0x89d1ca0, 0x10, 0xc3d05289, 0x15726f7b, 0x93e43866, 0xc042d0bd, 0x75832ac, 0xc6690d42, 0xd013c950, ...)
	/home/pi/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:411 +0x338
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).Synchronise(0x24bac80, 0x89d1ca0, 0x10, 0xc3d05289, 0x15726f7b, 0x93e43866, 0xc042d0bd, 0x75832ac, 0xc6690d42, 0xd013c950, ...)
	/home/pi/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:323 +0x5c
github.com/ethereum/go-ethereum/eth.(*ProtocolManager).synchronise(0x24921b0, 0x8a24e80)
	/home/pi/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/sync.go:190 +0x1b0
created by github.com/ethereum/go-ethereum/eth.(*ProtocolManager).syncer
	/home/pi/go-ethereum/build/_workspace/src/github.com/ethereum/go-ethereum/eth/sync.go:155 +0x17c
```

**Comment by m0ar** [comment]
> @m0ar the first crash you had -- do you know if that was the exact _same_ crash as this one? I'm thinking that maybe the first crash left the db a bit corrupted, and now you're hitting this because some data is missing in the db.
> 
> Also, what hardware are you running on ? What's the ram size?

I'm not sure, could be. Would a resync be the only solution then?

It's this setup: https://kauri.io/article/9695fcca217f46feb355245275835fc0 
(RaspberryPi 4B /w 4GB and a 500GB samsung SSD)

**Comment by diglos** [comment]
Hi.

I'm currently doing a fast sync on the Pi 4 and ran into this error (full log attached):

```
Oct 21 22:47:58 ethnode-9efbf7ff geth[526]: runtime: pointer 0x8f8fe000 to unallocated span span.base()=0x8c1be000 span.limit=0x2761dfe0 span.state=3
Oct 21 22:47:58 ethnode-9efbf7ff geth[526]: runtime: found in object at *(0x3834c00+0x320)
Oct 21 22:47:58 ethnode-9efbf7ff geth[526]: object=0x3834c00 s.base()=0x3830000 s.limit=0x3835f00 s.spanclass=88 s.elemsize=4864 s.state=mSpanInUse
```

It happened just once and the sync process seems normal (seems a pointer bug but I'm not sure if it is related to this issue). Just in case it helps. I will report back when the fast sync completes.

Setup:

- Raspberry Pi 4 4GB RAM
- --cache 512
- Swap: 4GB
- Disk: SSD Kingston 480GB with SATA-USB case (ASMedia ASM1153E chipset)

@m0ar, if you do a resync, would you mind to try this image?

https://ethraspbian.com/downloads/image_2019-10-20-EthRaspbian2.0-lite.zip

Just flash it and the fast sync process will start in 2-3 minutes (keep in mind that it will wipe out your entire USB disk and reinstall everything). Login ethereum:ethereum. You will be prompted to change the password on first login.

[geth-bad-pointer-error-rp4.txt](https://github.com/ethereum/go-ethereum/files/3766596/geth-bad-pointer-error-rp4.txt)

**Comment by diglos** [comment]
Hi.

Fast sync process was completed in 4 days. But, I got lots of errors like this one:

```
Oct 26 09:19:28 ethnode-9efbf7ff geth[16298]: runtime: out of memory: cannot allocate 279183360-byte block (2246934528 in use)
Oct 26 09:19:28 ethnode-9efbf7ff geth[16298]: fatal error: out of memory
Oct 26 09:19:28 ethnode-9efbf7ff geth[16298]: runtime stack:
Oct 26 09:19:28 ethnode-9efbf7ff geth[16298]: runtime.throw(0xb64f9a, 0xd)
```

It turns out that setting the cache to 256 MB (it was 512MB) solved this and Geth runs fine. But, somehow this is weird as with other 2 ARM boards (ARM64) I was using the default cache value (a little more that 1GB) and never ran into this (and both devices have 4GB RAM as well). Is it possible that this errors are caused by some problem with Go's GC?

**Comment by diglos** [comment]
Hi, got another error:

```
Oct 29 21:40:06 ethnode-9efbf7ff geth[7985]: INFO [10-29|21:40:06.773] Imported new block headers               count=1    elapsed=20.904ms     number=8836401 hash=9993f4…8f53dc age=1m28s
Oct 29 21:40:06 ethnode-9efbf7ff geth[7985]: panic: runtime error: slice bounds out of range [:37:34]
Oct 29 21:40:06 ethnode-9efbf7ff geth[7985]: goroutine 1320563 [running]:
Oct 29 21:40:06 ethnode-9efbf7ff geth[7985]: github.com/ethereum/go-ethereum/vendor/github.com/golang/snappy.load32(...)
Oct 29 21:40:06 ethnode-9efbf7ff geth[7985]: #011/home/travis/gopath/src/github.com/ethereum/go-ethereum/vendor/github.com/golang/snappy/encode_other.go:10
Oct 29 21:40:06 ethnode-9efbf7ff geth[7985]: github.com/ethereum/go-ethereum/vendor/github.com/golang/snappy.encodeBlock(0x50148141, 0x46, 0x46, 0x50aee200, 0x22, 0x200, 0x12a684c8)
Oct 29 21:40:06 ethnode-9efbf7ff geth[7985]: #011/home/travis/gopath/src/github.com/ethereum/go-ethereum/vendor/github.com/golang/snappy/encode_other.go:176 +0x900
Oct 29 21:40:06 ethnode-9efbf7ff geth[7985]: github.com/ethereum/go-ethereum/vendor/github.com/golang/snappy.Encode(0x50148140, 0x47, 0x47, 0x0, 0x0, 0x0, 0x200, 0x0, 0x0)
Oct 29 21:40:06 ethnode-9efbf7ff geth[7985]: #011/home/travis/gopath/src/github.com/ethereum/go-ethereum/vendor/github.com/golang/snappy/encode.go:37 +0x260
Oct 29 21:40:06 ethnode-9efbf7ff geth[7985]: github.com/ethereum/go-ethereum/p2p.(*rlpxFrameRW).WriteMsg(0x22038b80, 0x1f, 0x0, 0x22, 0xdf1f98, 0x506e4440, 0x0, 0x0, 0x0, 0x0, ...)
Oct 29 21:40:06 ethnode-9efbf7ff geth[7985]: #011/home/travis/gopath/src/github.com/ethereum/go-ethereum/p2p/rlpx.go:601 +0xc8
Oct 29 21:40:06 ethnode-9efbf7ff geth[7985]: github.com/ethereum/go-ethereum/p2p.(*rlpx).WriteMsg(0x20b7f280, 0x1f, 0x0, 0x22, 0xdf1f98, 0x506e4440, 0x0, 0x0, 0x0, 0x0, ...)
Oct 29 21:40:06 ethnode-9efbf7ff geth[7985]: #011/home/travis/gopath/src/github.com/ethereum/go-ethereum/p2p/rlpx.go:102 +0xe8
Oct 29 21:40:06 ethnode-9efbf7ff geth[7985]: github.com/ethereum/go-ethereum/p2p.(*protoRW).WriteMsg(0x21d8c1e0, 0x1f, 0x0, 0x22, 0xdf1f98, 0x506e4440, 0x0, 0x0, 0x0, 0x0, ...)
Oct 29 21:40:06 ethnode-9efbf7ff geth[7985]: #011/home/travis/gopath/src/github.com/ethereum/go-ethereum/p2p/peer.go:412 +0x15c
Oct 29 21:40:06 ethnode-9efbf7ff geth[7985]: github.com/ethereum/go-ethereum/p2p.Send(0xa5820030, 0x21d8c1e0, 0xf, 0x0, 0xa09728, 0x5954c5a0, 0x0, 0x0)
Oct 29 21:40:06 ethnode-9efbf7ff geth[7985]: #011/home/travis/gopath/src/github.com/ethereum/go-ethereum/p2p/message.go:101 +0xa0
Oct 29 21:40:06 ethnode-9efbf7ff geth[7985]: github.com/ethereum/go-ethereum/eth.(*peer).RequestReceipts(0x20cffd00, 0x1c8063a0, 0x1, 0x1, 0xa19b711e, 0xdfeb7436)
Oct 29 21:40:06 ethnode-9efbf7ff geth[7985]: #011/home/travis/gopath/src/github.com/ethereum/go-ethereum/eth/peer.go:351 +0x128
Oct 29 21:40:06 ethnode-9efbf7ff geth[7985]: created by github.com/ethereum/go-ethereum/eth/downloader.(*peerConnection).FetchReceipts
Oct 29 21:40:06 ethnode-9efbf7ff geth[7985]: #011/home/travis/gopath/src/github.com/ethereum/go-ethereum/eth/downloader/peer.go:203 +0x20c
Oct 29 21:40:07 ethnode-9efbf7ff systemd[1]: geth.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
```
I don't know if they are related. Let me know if you want me to open a separate issue.

**Comment by diglos** [comment]
Hi,

I did another Fast Sync with Geth 1.9.7. This time I only ran into an unallocated span issue (see attached). It seems that the out of memory issues were a Go problem, I will keep monitoring the process in the coming days though.

[geth-pointer-unallocated-span.txt](https://github.com/ethereum/go-ethereum/files/3850595/geth-pointer-unallocated-span.txt)

**Comment by m0ar** [comment]
@holiman 

Did a re-sync, this is the initial crash (that once again occured, now on v1.9.8): 
https://gist.github.com/m0ar/417aa0a4af2ba0f7e16760d29468e880

**Comment by m0ar** [comment]
Worth noting is also that I can get past these crashes when I restart the service, until it inevitably happens again. 

@diglos Did you get anywhere investigating GC issues?

**Comment by diglos** [comment]
Hi
I keep getting lots of out of memory errors once the sync is completed. It keeps happening until the Pi is unusable. So:

- During sync, as reported above, throws a pointer 0x82d61000 to unallocated span error
- Once synced, lots of fatal error: out of memory crashes

I'm currently doing another fast sync with 1.9.8 and already got a unallocated span error. Let's see how it ends but I think I will get the same errors.

Yesterday I got a report from a Eth on ARM Raspi 4 user (same problem, I think). Please attached find his log.

This doesn't happen at all on the NanoPC-T4 (4 GB RAM as well but ARM64)

Regards!

[geth-out-of-memory.txt](https://github.com/ethereum/go-ethereum/files/3902202/geth-out-of-memory.txt)

**Comment by m0ar** [comment]
@diglos Yeah my Pi gets borked after a night of OOM crashes too, until it stops responding to SSH and needs a hard reboot

**Comment by diglos** [comment]
Hi all.

It seems that this is a 32bit kernel thing. There are lots of issues about out of memory and oom crashes on the Raspberry Pi forums [1].

Raspbian enabled recently a 64bit kernel for the Raspberry Pi 4 which seems to work great handling 4GB of RAM (this is just the kernel, the userspace is still on 32bit). Once enabled, I completed a Fast Sync and it’s been running for 1 day with no issues whatsoever (with 256MB cache).

I’m releasing early next week a new image of Ethereum on ARM for the Raspberry Pi 4 with this kernel enabled by default.

@moar, you can enable the 64bit kernel just by adding the proper option to config.txt (first, make sure you have the latest firmware):

```
sudo rpi-eeprom-update
sudo echo arm_64bit=1 >> /boot/config.txt
```

And reboot.

This should fix the memory issues.

[1] https://www.raspberrypi.org/forums/viewtopic.php?t=255433
https://www.raspberrypi.org/forums/viewtopic.php?t=249924
https://www.raspberrypi.org/forums/viewtopic.php?t=244367
https://www.raspberrypi.org/forums/viewtopic.php?t=244849
https://www.raspberrypi.org/forums/viewtopic.php?t=244531

**Comment by sirnicolas21** [comment]
> Hi all.
> 
> It seems that this is a 32bit kernel thing. There are lots of issues about out of memory and oom crashes on the Raspberry Pi forums [1].
> 
> Raspbian enabled recently a 64bit kernel for the Raspberry Pi 4 which seems to work great handling 4GB of RAM (this is just the kernel, the userspace is still on 32bit). Once enabled, I completed a Fast Sync and it’s been running for 1 day with no issues whatsoever (with 256MB cache).
> 
> I’m releasing early next week a new image of Ethereum on ARM for the Raspberry Pi 4 with this kernel enabled by default.
> 
> @moar, you can enable the 64bit kernel just by adding the proper option to config.txt (first, make sure you have the latest firmware):
> 
> ```
> sudo rpi-eeprom-update
> sudo echo arm_64bit=1 >> /boot/config.txt
> ```
> 
> And reboot.
> 
> This should fix the memory issues.
> 
> [1] https://www.raspberrypi.org/forums/viewtopic.php?t=255433
> https://www.raspberrypi.org/forums/viewtopic.php?t=249924
> https://www.raspberrypi.org/forums/viewtopic.php?t=244367
> https://www.raspberrypi.org/forums/viewtopic.php?t=244849
> https://www.raspberrypi.org/forums/viewtopic.php?t=244531

still getting the error even with that fixed

> uname -a
> Linux raspberrypi 4.19.93-v8+ #1286 SMP PREEMPT Mon Jan 6 13:29:56 GMT 2020 aarch64 GNU/Linux

>

**Comment by diglos** [comment]
Hi :-)

It's been a while... We successfully  synced a Raspberry Pi 4 running an Ubuntu 20.04 64 bit and we didn't get any crash or memory allocation problem. As we expected this seems to be a 32bit OS problem.

@m0ar please, take a look at this:

https://www.reddit.com/r/ethereum/comments/gf3nhg/ethereum_on_arm_raspberry_pi_4_images_release/

Regards!

**Comment by adamschmideg** [comment]
Thank you @diglos

**Comment by willianpaixao** [comment]
Hi @adamschmideg, just noting that the users moving to ARM64, but ARMv7 is still broken. This issue still persists and shouldn't be closed.
