### ISSUE TITLE
web3.exceptions.BadFunctionCallOutput: Could not decode contract function call func return data b'' for output_types ['uint256']

### ISSUE THREAD

**Issue by avatar-lavventura** [ethereum/go-ethereum#20785]
For clearity I am using two different ubuntu machines as follows, please note that both machines are sync to my private black chain and working on the same smart-contract: 

I was using `web3py` to communicate with my contract. My contract call was working on geth `v1.9.9` where it starts not to work on `v1.9.13`. I am not sure which version in between cause this error.

=> **ubuntu-a** uses: 
```
- web3==5.7.0`, Python `3.6.8`, OS: `linux` on `venv`
- geth Version: 1.9.9-stable

Ubuntu 18.04.3 LTS
Release:	18.04
Codename:	bionic
```

-------

=> **ubuntu-b** uses: 
```
- On `web3==5.7.0`, Python `3.7.5` on `venv` I have also tried for Python `3.6.8`
- geth Version: 1.9.13-unstable

Ubuntu 19.10
Release:	19.10
Codename:	eoan
```

----

Following function call works using `web3py` on **ubuntu-a** which has (geth Version: 1.9.9-stable): but when I upgrade the geth version to geth Version: 1.9.13-unstable it starts not to work.

```
contract.functions.getReceivedStorageDeposit(b'97fc72c7b24e499b79cb9e2d42300ad1').call()
```

where the function has the following signature:

```solidity
function getReceivedStorageDeposit(bytes32 sourceCodeHash)
    external
    view
    whenProviderRegistered returns (uint256)
```

------

On **ubuntu-b**, I get the following error message:

```
Traceback (most recent call last):
  File "/home/alper/venv/lib/python3.7/site-packages/web3/contract.py", line 1432, in call_contract_function
    output_data = web3.codec.decode_abi(output_types, return_data)
  File "/home/alper/venv/lib/python3.7/site-packages/eth_abi/codec.py", line 181, in decode_abi
    return decoder(stream)
  File "/home/alper/venv/lib/python3.7/site-packages/eth_abi/decoding.py", line 127, in __call__
    return self.decode(stream)
  File "/home/alper/venv/lib/python3.7/site-packages/eth_utils/functional.py", line 45, in inner
    return callback(fn(*args, **kwargs))
  File "/home/alper/venv/lib/python3.7/site-packages/eth_abi/decoding.py", line 173, in decode
    yield decoder(stream)
  File "/home/alper/venv/lib/python3.7/site-packages/eth_abi/decoding.py", line 127, in __call__
    return self.decode(stream)
  File "/home/alper/venv/lib/python3.7/site-packages/eth_abi/decoding.py", line 198, in decode
    raw_data = self.read_data_from_stream(stream)
  File "/home/alper/venv/lib/python3.7/site-packages/eth_abi/decoding.py", line 308, in read_data_from_stream
    len(data),
eth_abi.exceptions.InsufficientDataBytes: Tried to read 32 bytes.  Only got 0 bytes

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "koo.py", line 5, in <module>
    eBlocBroker.functions.getReceivedStorageDeposit(b"").call()
  File "/home/alper/venv/lib/python3.7/site-packages/web3/contract.py", line 904, in call
    **self.kwargs
  File "/home/alper/venv/lib/python3.7/site-packages/web3/contract.py", line 1454, in call_contract_function
    raise BadFunctionCallOutput(msg) from e
web3.exceptions.BadFunctionCallOutput: Could not decode contract function call getReceivedStorageDeposit return data b'' for output_types ['uint256']
```

**[Q]** What may cause this error? How can I fix it?

**Comment by karalabe** [comment]
I have a hunch. We've merged in a change to `eth_call` so that it will not default to your first account if you don't specify any sender (rather to 0x00). This was made to make the operations more predictable in different environments. Does your node have accounts in it? Are you explicitly specifying the sender for these data retrievals or relying on Geth to do whatever?

**Comment by avatar-lavventura** [comment]
Seems like that was the main cause of the bug. Yes my node has accounts.

I was calling as follows, where inside `call()` was empty:

`self.eB.functions.getReceivedStorageDeposit(self.job.provider, self.job.requester, source_code_hash).call()`

adding `from:` option fixed the problem.

`self.eB.functions.getReceivedStorageDeposit(self.job.provider, self.job.requester, source_code_hash).call({"from": self.w3.toChecksumAddress(PROVIDER_ID)})`

**Comment by karalabe** [comment]
Sweet. Thanks for confirming.

We kind of knew that there's a slight chance we might break something. Unfortunately the old behavior was super quirky and unpredictable, so we thought we should just bit the bullet and fix it. Originally we wanted to error out if no address was specified but we thought that might be extreme.

In your case, apparently your contract execution does depend on the sender, in which case you really should always configure it properly.

**Comment by avatar-lavventura** [comment]
I first thought it could be related to `web3py` or `ubuntu` version. At last I check `geth` :)

Interestingly my contract execution seems like not related to `msg.sender`, but seems like it still get effected. Anyway I will fix all my `call()`s including the `from:`


My called function:

```
    function getReceivedStorageDeposit(address _provider, address requester, bytes32 sourceCodeHash)
   external view
        whenProviderRegistered returns (uint256)
    {
        return providers[_provider].storageInfo[requester][sourceCodeHash].received;
    }
```

**Comment by karalabe** [comment]
> Interestingly my contract execution seems like not related to msg.sender, but seems like it still get effected. 

That's quit strange. Can you share a snippet perhaps of what you're doing in the contract?

**Comment by karalabe** [comment]
What does `whenProviderRegistered` do?

**Comment by avatar-lavventura** [comment]
Ah my bad, I forget to check that section.  

```
    modifier whenProviderRegistered {
        require(providers[msg.sender].committedBlock > 0); 
        _;
    }
```

**Comment by karalabe** [comment]
:D Ok, that explains it then :)
