### ISSUE TITLE
getTransaction returns null for old transaction

### ISSUE THREAD

**Issue by gaiazov** [ethereum/go-ethereum#2434]
#### System information

Geth version: 1.3.6
OS & Version: Windows 10 64-bit

#### Expected behaviour
On a fully synchronized instance of geth, I can get an old (150'000 blocks behind) transaction by the transaction hash

`eth.getTransaction("0xd68a4d79edd07d593389bf6698055b3b41bfe80a68caa30834f26ae0166623c4")` should return a transaction from block 1154410

#### Actual behaviour
The geth node is fully synchronized with the network and does not report any corruption. I started the node 1 day ago and did not use it to send any transactions or mining. Basically a clean node that just synchronized

`eth.getTransaction("0xd68a4d79edd07d593389bf6698055b3b41bfe80a68caa30834f26ae0166623c4")` returns `null`

`eth.getTransactionFromBlock(1154410, 0)` returns the correct transaction

Same behavior on `1.4.0-unstable`

#### Steps to reproduce the behaviour
`eth.getTransaction("0xd68a4d79edd07d593389bf6698055b3b41bfe80a68caa30834f26ae0166623c4")`

#### Backtrace

````
C:\geth>geth attach
instance: Geth/v1.3.6/windows/go1.5.1
 datadir: C:\Users\Leonid\AppData\Roaming\Ethereum
coinbase: 0xea52c48e51c8ad1f916cf6ae379553e549c3251e
at block: 1298864 (Fri, 08 Apr 2016 08:02:40 EDT)
modules: admin:1.0 db:1.0 debug:1.0 eth:1.0 miner:1.0 net:1.0 personal:1.0 shh:1.0 txpool:1.0 web3:1.0
> eth.getTransaction("0xd68a4d79edd07d593389bf6698055b3b41bfe80a68caa30834f26ae0166623c4")
null
> eth.getTransactionReceipt("0xd68a4d79edd07d593389bf6698055b3b41bfe80a68caa30834f26ae0166623c4")
null
> eth.getTransactionFromBlock(1154410, 0)
{
  blockHash: "0x645f329a6ba1a5643dda21e0a19b8909f353cd34858f3123d172b32826c0a295",
  blockNumber: 1154410,
  from: "0x1f93b5e75a04b225816935c3d65f552cac88a61b",
  gas: 250000,
  gasPrice: 52000000000,
  hash: "0xd68a4d79edd07d593389bf6698055b3b41bfe80a68caa30834f26ae0166623c4",
  input: "0x3ed4867900000000000000000000000052f6ae7b0dd201cf110daa75be9ce03512ff8e420000000000000000000000000000000000000000000000000000000056e80c8400000000000000000000000000000000000000000000000000000000000000c000000000000000000000000000000000000000000000000000000000000001200000000000000000000000007fb3b877f2d85d92d4172764ea5cd68982cbe53e00000000000000000000000000000000000000000000000000000000047868c00000000000000000000000000000000000000000000000000000000000000002e00e8bcc546c82195d0b21fabf0cb116b62bee11645d20416a50c104f4ec6b3d0f421a20b4da2a1f56fed5ac32ca8a7e46e2f65480f8a97949bd2b278038a4480000000000000000000000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000001c",
  nonce: 21371,
  to: "0x9af09991ad63814e53ffc1bccf213ee74027608b",
  transactionIndex: 0,
  value: 1
}
>
````

running geth with `--verbosity "6"`
````
I0408 08:05:05.510153    6928 ipc.go:124] new connection with id 153551 started
I0408 08:05:05.510663    6928 mergedapi.go:61] admin_enableUserAgent "W10="
I0408 08:05:05.511133    6928 types.go:106] Generated response: *shared.SuccessResponse &{%!s(float64=0) 2.0 %!s(bool=true)}
I0408 08:05:05.512156    6928 mergedapi.go:61] eth_getTransactionByHash ["0xd68a4d79edd07d593389bf6698055b3b41bfe80a68caa30834f26ae0166623c4"]
I0408 08:05:05.513632    6928 types.go:106] Generated response: *shared.SuccessResponse &{%!s(float64=10) 2.0 <nil>}
````

**Comment by gaiazov** [comment]
I investigated more and it looks like this was caused by `--fast` sync option. I have narrowed it down to block `1288855`, after which, on my node, `getTransaction` returns null. That block was mined 2 days ago (April 6, 2016), which is the day I started syncing with network.

It does make sense to me that `--fast` sync option does not synchronize everything but as far as I know, this is **not very well documented**

**Comment by obscuren** [comment]
Thank you for this very detailed report. 

`eth.getTransaction` should return the same value as `eth.getTransactionFromBlock`. All this information is available is available, regardless of the `--fast` sync.

**Comment by karalabe** [comment]
I'll look into this. Perhaps there's a corner case with the pivot block when we switch from fast sync to full sync that something's not set in the database?

**Comment by karalabe** [comment]
@gaiazov Do **all** `getTransaction` invocations return null after some block number, or only a handful of transactions are missing?

All of the data is still there if you can retrieve it via `getTransactionFromBlock`, the only difference is that `getTransaction` has a special index to retrieve the data from, but it still uses the same data.

**Comment by gaiazov** [comment]
@karalabe as far as I can tell its all `getTransaction` calls return null before a certain block (which I assume the block when fast-sync started)

I wrote a small script
````javascript
_ = require('underscore-node');
var Web3 = require('web3');
var web3 = new Web3();

web3.setProvider(new web3.providers.HttpProvider('http://localhost:8545'));

var fromBlockNumber = 1288865; // educated guess
var toBlockNumber = fromBlockNumber - 100;
var nullTransactionsCount = 0;

var blockNumber = fromBlockNumber;

while (blockNumber > toBlockNumber) {
	console.log('block ' + blockNumber);
	var block = web3.eth.getBlock(blockNumber);
	_.each(block.transactions, function(tx){
		try {
			var hash = tx;
			var transaction = web3.eth.getTransactionReceipt(hash);
			if (transaction === null) {
				console.log(' > transaction ' + hash + ' is null');
			} else {
				console.log(' > transaction ' + hash)
			}
		} catch (err) {
			console.error(err);
		}
	});
	blockNumber--;
}
````

which outputs
````
C:\geth>node tx.js
block 1288865
 > transaction 0x2f46ccbed958cb6732e4921d2622bd9ec5b935058224c449bcc012b6ed0eac6b
 > transaction 0xab0626d957ec681fb46b243a544a8397f4f2a1a48802786c49f8ad7bea6cc8a1
 > transaction 0x60e547b61c6c666da9d44dbe15b2307f9f092350cc026d81afd3d4ae9a9dfa0b
 > transaction 0x24ad815635db774840e7cc5961dd10cf19ee5def35046866f20a0f0a64dd5aa0
 > transaction 0x6ea3cee9c8b50f5330e63005d809656e2a0dfeeccacf106fb923ebb540ccceaa
block 1288864
 > transaction 0xd4c9a378037847949e63050d425ccc2694ef1daa9b1675e867f59d2478f9787c
 > transaction 0x5db50da68fa603997da7649bea66a2a3966fa58b0263e2902000b8df8d1f48ec
 > transaction 0xdc63df0d6c4a7acbb115b0f03bb8251030ff735550a7870bef202573975f3267
 > transaction 0x2ff04b13ab3381bca76c6302ac5382849f91891a1472c42d2365690111da830f
 > transaction 0x2867560a360eb0ce4b66375dc47f30750637501216b6162927441169118880da
 > transaction 0x922a44f7c05fc538b42c10deeef7c4bd71e3f04c2793c5008e383f926feb6caf
 > transaction 0x9d8458dd1905018395b9336d3b26986f29549ce9070d92b238177cd62852f2af
block 1288863
block 1288862
block 1288861
 > transaction 0xf01a3cd1f3f25a506b870ca2108bf9752025155feb542c1f8449b6c2fcf326a5
block 1288860
 > transaction 0x5f264cbe64c2b1fe9846f4c7d65a8830e6574a58e574a3c8cf28f7b24120a3ba
 > transaction 0xa0f5818f164b0a35bd1baaec612e7b36e52e9e188a2aee4880fb6a29a0d87031
block 1288859
block 1288858
 > transaction 0x01f0dd85dfa39c5220b39a5696abcefb53631191ff4264a4895abb73941edd38
 > transaction 0x3bd3a222418cd197a976206f5b2dae58e903b9ac3363e303eff4dd4fe12f5ecd
 > transaction 0xfaeefac02ac97f74af9441ae1330e22630acf42f31602c4e2f959a08a548a2f2
 > transaction 0xaf06d8deb9ea9289cd97d61b16702d91a7ef4834dd69ce14dcf7d7fc54cf7eea
 > transaction 0xda6577c88e64c2364ac90400c488ccc108ee7322457d4b59e16e1f152beeca92
 > transaction 0x726c179aec87fcff3314451311d92e54f47bd1f110739c28b15cc4114c26da84
 > transaction 0xa73ef57a0c32acecd5e0fd4cb026ac6034ed9e3ba6708a646be314b9fb4acba3
block 1288857
 > transaction 0xcf4297f5c32b73f0880c511077b2af4ed95ce4e1391c67797f8d4c96c147d69a
 > transaction 0xc2698a6c44287ee65c2ffe45e0668034b04816cf41564a1650bf22b92a2c60ff
 > transaction 0xc4306b753f0b9d9968c68fefa2d7f9bae9adce9432436f5ce220fabcd7451655
 > transaction 0x97da77a4b587f5646bfafa02a402525786c1fdbafb0f560faac49b02dbc00916
block 1288856
block 1288855
 > transaction 0x9c2c290131990660adc7b488efee89c9a4bd85554549fa8145a743a7fb1b27ac is null
 > transaction 0x730075b88c5935ca001dea025a6a7866787fa670fc1ec6479ced86b2c8878f3b is null
 > transaction 0xba2852578b5d91cb14946673e3b977939bf5dbc02bc9197e8b7ce22a749424aa is null
 > transaction 0xe4cda8cafbe133e2a4ee8769b9c792ae009bd1ae65991e8ce14aad2f530ea43e is null
 > transaction 0x1164a1ab921a7a25e2b683ca1b3ecd9e14cecc1b857d0289742c7e036791d707 is null
 > transaction 0x224cc223546c66877e4acffca3ba0ad6d935f01fd04e1648bdc73bee87830bbe is null
 > transaction 0x32b0ed29431123852412fae3a1f7a03abe2023a1742ed86d0455926817d388db is null
 > transaction 0x8e12226ee893f0c644f0159850a51acf64be2ec1eb72012b1bdd87224b5318ef is null
 > transaction 0xb7fcd5ae87acf6d937ab08d9220021f3a2f60898761d9db1ab02f358e830eb33 is null
 > transaction 0xd82b6410e41933d092d1f1d370a277b1a711f1ab97bb98786bd2d7ece79357f7 is null
 > transaction 0x671ce5fb0645eb2718d5eb619c853d75ca53b9502206594f4d9add411c83796d is null
 > transaction 0x9d9f1fe4c29617bee92ebb917a381e2bcc04ce12b9e6bf5ba6e7d5cbd8b3d9b4 is null
 > transaction 0x77a4a1d2256d658b94efdeadd02efaa59adb3020b5639c91d68bb16b64a4594b is null
 > transaction 0x03f1c3a6d7bdf19e808e222ee34ac4a05981c54ece723fddeeb70a9b7592bc05 is null
 > transaction 0x85d2254b284cfdee7572cecc42228b59d2446494e6ffe2a5b1079ddb93dfffae is null
 > transaction 0x7ddfe61c91ad78e2c5f959a718da4586f9088bfd1b01aec1236cbb1cdcbfa850 is null
 > transaction 0x545fa2038e95dbd9580f4194d9eb18aca095a385acf6f5211319d73fc2c0260b is null
 > transaction 0xd01a7cfa69af6d156cc26bda1bbd2b4171faf9a422c33cb53c71c372b98ec528 is null
 > transaction 0x7726772fc3652c1ca1080e07869d9fd144b7e187fb261a23705513eb05980339 is null
 > transaction 0x38607ffa844230b7e38a3f7b9abef2c4fcdb1bd0b119856927a96046e449b476 is null
block 1288854
 > transaction 0x7f3b2c33aabb2d69999014d1ae7da9f797dc423807ec4c07bac33dd96dc6e0e6 is null
 > transaction 0x5999c478703a25bc173dae3c20bc4273ec87f81d720970ca576601f5e8e532ae is null
 > transaction 0x66ef958ccddb0c74821821bd9815d61acf3f4977b7e2add7ac721a6bdb3107b7 is null
block 1288853
 > transaction 0xd10486df5c0e5804418ac7699c3cac67dbcc177cdd2f4b972f5a6abd5fce8904 is null
block 1288852
 > transaction 0xa41c369946893f1d807a464836a166360b2c57f29590ecfe2b366f5febb3509e is null
 > transaction 0x548311d9016b18c729398c3c4f3858653bbb583bfb6052db77cea3906c5daf1c is null
 > transaction 0xfd63245e78912dfd9eb96de763fd5cf45bfd1ad4d1f6eb9bd2d1d337aa24fc2c is null
 > transaction 0xa2dd70342688e7ab154a32e9b2709f34c5852522efff660e3f9168bfbc7e6aa9 is null
 > transaction 0x8c1d3956bde73df79166059fb906beb91dd542e94940b104f60fc974f23b3e0d is null
 > transaction 0x537c51749f0243613468f4ab4f4801f7d4ae8ab1acc2dd64ab2a42e78ed3bd41 is null
 > transaction 0x536c8e1ce566f88cbe1203d68c5500f4932b7aa0af0fcdb474dd33ec4adcaaa0 is null
block 1288851
 > transaction 0x1207d8e4d57f36504081916f6a97dca12990bfc90768a14c011ef97dd95c8a26 is null
block 1288850
 > transaction 0x2560ce81c2c2415074171a9bd6bce6292006c257be78584f29a92c3fbfd30112 is null
 > transaction 0xd71c5ec3e646c7d08fe412d1b0c41a2cc74a1465f44803df28b12c3b738cecf4 is null
 > transaction 0x846486fd4be0ed16fd767c744332248a165ae9ba3349eea349471466f2aa4779 is null
 > transaction 0xd616a3e1c939bbb90c524a0f5dd24b7c5315811f704b7598e3b08c92bd746e63 is null
 > transaction 0xc2c8a0771a2492d704443a79048fc9c614cb53a129c13ef83027a8f3968ee177 is null
 > transaction 0x31f4e92a67c38b08f79dd2135e08e700f618a4d6e8ef727a1f885d64b36c48fe is null
block 1288849
 > transaction 0xc24dd649c721e280742b1ab57cb33e6ced8da6a3e5a29bc1371487a334500459 is null
 > transaction 0x31aeeb3d32e528f014263251bb5865eba162d1f6b0e5e2623cf6d29ce3867c59 is null
````

so you can see that after block `1288855` I only get `null` from `getTransaction`

**Comment by karalabe** [comment]
I wrote a small script to iterate over the blockchain database and for every block, verify that the transactions can be retrieved individually:

```go
func verifyDB(ctx *cli.Context) {
	glog.Infoln("Verifying blockchain database")

	chain, db := utils.MakeChain(ctx)
	for i := uint64(0); i < chain.CurrentBlock().NumberU64(); i++ {
		block := chain.GetBlockByNumber(i)
		if block == nil {
			glog.Errorf("Failed to retrieve block #%d", i)
			return
		}
		glog.Infof("Block #%d: %x", block.NumberU64(), block.Hash())
		if block.NumberU64() != i {
			glog.Errorf("Block number mismatch: have %v, want %v", block.NumberU64(), i)
			return
		}
		for j, tx := range block.Transactions() {
			tx, bhash, bidx, tidx := core.GetTransaction(db, tx.Hash())
			switch {
			case tx == nil:
				glog.Errorf("Block #%d: failed to retrieve transaction #%d:", block.NumberU64(), j)
				return
			case bhash != block.Hash() || bidx != block.NumberU64():
				glog.Errorf("Block #%d: Tx #%d: block mismatch: #%d [%x]", block.NumberU64(), j, bidx, bhash)
				return
			case tidx != uint64(j):
				glog.Errorf("Block #%d: Tx #%d: index mismatch: %d", block.NumberU64(), j, tidx)
				return
			default:
				glog.Infof("Block #%d: Tx #%d: %x", block.NumberU64(), j, tx.Hash())
			}
		}
	}
}
```

I've ran it on my currently active main chain and also did a fresh fast sync on the testnet and ran it on that one. Both passed all verifications, reporting no missing transactions.

This leads to two potential possibilities:

 - The missing transaction bug is in some very strange part of the code, possibly some failure/recovery scenario isn't handled properly and/or a chain reorg isn't done as it should be.
 - The bug was in the stable branch and already fixed on develop (I only have chains synced with develop).

**Comment by karalabe** [comment]
@gaiazov Ah awesome, I'll run your tester too to see if it finds anything. Maybe it's an RPC issue.

In the mean time:

 - Did you by any chance mine during syncing? Not sure how that would interfere with fast sync.
 - Did you sync with the stable geth? (upgrading post sync doesn't help, as a database index seems to be missing)

**Comment by karalabe** [comment]
@gaiazov Ran your code (a bit tuned up though) and seems to not report any issues on my database. I'll try a fast sync with the stable branch to see if it was an issue we've already fixed. If you don't have anything better to do, maybe try a fresh fast sync on develop? :)

Btw, this is my souped up version of your code. It uses IPC is is blazing fast compared to HTTP RPC.

```js
_ = require('underscore-node');
var Web3 = require('web3');
var net = net || require('net');
var web3 = new Web3();

web3.setProvider(new web3.providers.IpcProvider('/tmp/fasttest/testnet/geth.ipc', net));

var fromBlockNumber = 738904; // educated guess
var toBlockNumber = 0;
var nullTransactionsCount = 0;

function verify(number) {
  console.log('block ' + number);
  var block = web3.eth.getBlock(number, function(error, block) {
    _.each(block.transactions, function(tx){
        try {
            var hash = tx;
            var transaction = web3.eth.getTransactionReceipt(hash, function(error, tx) {
              if (transaction === null) {
                  console.log(' > transaction ' + hash + ' is null');
              } else {
                  console.log(' > transaction ' + hash)
              }
            });
        } catch (err) {
            console.error(err);
        }
    });
    verify(number-1)
  });
}
verify(fromBlockNumber);
```

**Comment by karalabe** [comment]
Tried a fast sync from scratch on the main network using Geth 1.4. Restarted it a few times, rolled back headers a few times. Even did restarts immediately after a rollback. Checked and all transactions are accounted for. I'll repeat the test for Geth 1.3.x but at this point it would seem to me that it's a bug we've fixed during the major core refactors that we did during these last months.

**Comment by almindor** [comment]
I have the same behavior with 1.3.6 fully synced from 0 block to now using --fast option. All my transactions are missing, even RPC calls (eth_getTransactionByHash) report nulls.

Will try with 1.4.0 sometime tomorrow with same chain and then resync.

**Comment by gaiazov** [comment]
Yep, the chaindata from 1.3.6 is not good and the ultimate solution is to delete old chaindata and do fast-sync with 1.4.0 or later. In the meantime, I worked around the issue by using `getTransactionFromBlock` which still works in 1.3.6
I'm going to close this issue

**Comment by khushalkunjir** [comment]
I did not bring up the node with --fast syncmode="full" only but still facing issue for getting old transaction details can you please help me.
