### ISSUE TITLE
GraphQL/JSON-RPC logs regression between 1.10.21 & 1.10.22

### ISSUE THREAD

**Issue by SLoeuillet** [ethereum/go-ethereum#25583]
#### System information

Geth
Version: 1.10.22-stable
Git Commit: 2de49b04e56cf07f011d6d91f9d5c08847aabe8e
Architecture: amd64
Go Version: go1.18.5
Operating System: linux
GOPATH=
GOROOT=go

Archive node

#### Expected behaviour

Doing a complex GraphQL query returns correct data from a block, like in 1.10.21

#### Actual behaviour

Too much data (logs unrelated to current block)

#### Steps to reproduce the behaviour

Going to GraphQL UI : http://xxxxx:8545/graphql/ui

Type the following query :

```
{
  block(number: 15401505) {
    number
    transactions {
      logs {
        account {
          address
        }
      }
    }
  }
}

```

#### More details

That block on etherscan : https://etherscan.io/block/15401505

On a 1.10.22 node, this query returns 257386 lines, which is a bit too much (could depend on when you run the request)
On a 1.10.21 node, this query returns 2209 lines, which seems more in the norm

**Comment by SLoeuillet** [comment]
createdContract : 163 on both sides
account : 51345 (1.10.22) vs 315 (1.10.21)

**Comment by SLoeuillet** [comment]
So, I'd say it is the "logs" part

**Comment by SLoeuillet** [comment]
I suppose it is linked to https://github.com/ethereum/go-ethereum/pull/25459

**Comment by s1na** [comment]
Hey, thanks for reporting it. The problem was that after my changes graphql was returning all of the block logs for each transaction, blowing up the response. If you get a chance to try the linked PR, the issue should be resolved.

**Comment by SLoeuillet** [comment]
I would build and test it on monday morning. Thanks for the fix

**Comment by SLoeuillet** [comment]
@s1na  fix tested on my personal node, works perfectly, thanks

**Comment by yiteng-guo** [comment]
@s1na I'm still seeing the regression on my end (build on d30e39b2f). I ran the following graphql
```
{
  block(hash: "0xfd29823bf38d3bab5877d4ffeae448755b9da47c7e4e6fac6988e0bed043abd6") {
    number
    transactions {
      hash
      logs {
        account {
          address
        }
        topics
      }
    }
  }
}
```
no logs returns for `0xe7ac6b6b01f5be91d3dbaf797059e5a18117b25f6960be1b83cefa538dffc330` but this tx does have log https://etherscan.io/tx/0xe7ac6b6b01f5be91d3dbaf797059e5a18117b25f6960be1b83cefa538dffc330#eventlog

**Comment by SLoeuillet** [comment]
I confirm that with that very same version d30e39b , logs is sometimes empty, sometimes not

**Comment by SLoeuillet** [comment]
geth 1.10.21 :
[geth00_15520795.log](https://github.com/ethereum/go-ethereum/files/9548169/geth00_15520795.log)

geth 1.11.0 d30e39b :
[geth01_15520795.log](https://github.com/ethereum/go-ethereum/files/9548168/geth01_15520795.log)

**Comment by donatocayurin** [comment]
Thank you ❤️🙏

**Comment by donatocayurin** [comment]
❤️🙏
