### ISSUE TITLE
Geth v.1.13.4 - BAD BLOCK - Invalid merkle root - Error when I make a transaction

### ISSUE THREAD

**Issue by Alessandro-Cavaliere** [ethereum/go-ethereum#28403]
#### System information

Geth version: `1.13.4`
OS & Version: Linux

#### Expected behaviour

The expected result is that transactions are distributed to other blocks without problems.

#### Actual behaviour

> I'm running my own **3 node PoA** private blockchain and trying to notarize on the blockchain some hashes. I moved forward with an old problem of mine, which I haven't been able to solve yet: #28154 

Every single node is on different Linux Machines with its own IP address.
I have tried every configuration and every test to resolve this **BAD BLOCK** error, but I still haven't been able to fix it.

I think I have understood the reason why the Geth system (in my specific case) returns this particular error.

Doing some tests, I noticed that if in Genesis I set only one address referring to a single node as a signatory and leave the aforementioned node active, the network works perfectly. Unfortunately, having only one active node is not the best scenario, so inevitably I created others.

The very strange thing is that as soon as the transaction that is signed by node1 is also distributed to node2 or node3, they receive the BAD BLOCK error with this message printed in the console:

```
ERROR[10-23|10:23:36.122]
########## BAD BLOCK #########
Block: 1 (0x6a637401abc1a0f02e78370bc784ee287266d4c5c96130b102f6a6ad7ee6416a)
Error: invalid merkle root (remote: 553a56549abc5983be0fd3104c4ff67e2c027b62a546f390ed0b253a8ad5910e local: d59864e270767ad01542ae4eff5d921e033b9ef8d2f9922a46e0422793f13184) dberr: %!w(<nil>)
Platform: geth (devel) go1.21.3 amd64 linux
VCS: 3f907d6a-20231017
Chain config: &params.ChainConfig{ChainID:10002, HomesteadBlock:0, DAOForkBlock:<nil>, DAOForkSupport:false, EIP150Block:0, EIP155Block:0, EIP158Block:0, ByzantiumBlock:0, ConstantinopleBlock:0, PetersburgBlock:0, IstanbulBlock:0, MuirGlacierBlock:0, BerlinBlock:0, LondonBlock:0, ArrowGlacierBlock:0, GrayGlacierBlock:0, MergeNetsplitBlock:<nil>, ShanghaiTime:(*uint64)(nil), CancunTime:(*uint64)(nil), PragueTime:(*uint64)(nil), VerkleTime:(*uint64)(nil), TerminalTotalDifficulty:<nil>, TerminalTotalDifficultyPassed:false, Ethash:(*params.EthashConfig)(nil), Clique:(*params.CliqueConfig)(0xc00073b3a0), IsDevMode:false}
Receipts:
  0: cumulative: 1227394 gas: 1227394 contract: 0x9415C968fC60A8313E0F519f625DE6484b635d74 status: 1 tx: 0x478df7f0c189aa68cdc8cb865f0bbae0f8453d8af3398a3e042866fe5b7f8879 logs: [] bloom: 00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 state:
##############################
ERROR[10-23|10:23:36.122] Failed to retrieve beacon bounds for bad block reporting err="beacon sync not yet started"
```
Below I try to give as much information as possible:

**genesis.json**
```
{ 
  "config": {
    "chainId": 10002,
    "homesteadBlock": 0,
    "eip150Block": 0,
    "eip155Block": 0,
    "eip158Block": 0,
    "byzantiumBlock": 0,
    "constantinopleBlock": 0,
    "petersburgBlock": 0,
    "istanbulBlock": 0,
    "muirGlacierBlock": 0,
    "berlinBlock": 0,
    "londonBlock": 0,
    "arrowGlacierBlock": 0,
    "grayGlacierBlock": 0,
    "clique": { 
      "period": 0,
      "epoch": 30000
    }
  },
  "difficulty": "1",
  "gasLimit": "800000000",
  "extradata": "0x000000000000000000000000000000000000000000000000000000000000000027984a6A85333156E1Ef86077A678eb9e020af500000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
  "alloc": { 
    "27984a6A85333156E1Ef86077A678eb9e020af50": { "balance": "100000000000000000000" },
	"66E98dC710cd9e91aaF9ecA8486367277Bbf14F8": { "balance": "100000000000000000000" }
  }
}
```

**node1 start command**
```
#!/bin/bash

#LOG_FILE="/var/log/mio_script.log"
#exec >> "$LOG_FILE" 2>&1

 

PUB_ADDR="0x27984a6A85333156E1Ef86077A678eb9e020af50" 
PRIVATE_IP_ADDR="<myprivIP>" 
PUBLIC_IP_ADDR="<mypubIP>" 
FILENAME_JS="nodi.js"

 

cd /home/ubuntu/
sudo ./geth_1_13_4/geth  \
	--datadir node1 \
	--networkid 10002 \
	--allow-insecure-unlock \
	--unlock $PUB_ADDR \
	--http \
	--port 30314 \
	--http.addr $PRIVATE_IP_ADDR \
	--http.port 8546 \
	--nat extip:$PUBLIC_IP_ADDR \
	--http.corsdomain '*' \
	--http.vhosts '*' \
	--http.api 'admin,eth,miner,net,txpool,personal,web3' \
	--syncmode full \
	--ipcdisable \
	--mine \
	--miner.etherbase $PUB_ADDR \
	--password "path/to/password.txt" \
	--authrpc.port 8552 \
	console
```
**node2 start command**
```
PUB_ADDR="0x66E98dC710cd9e91aaF9ecA8486367277Bbf14F8" 
PRIVATE_IP_ADDR="<myprivIP>" 
PUBLIC_IP_ADDR="<mypubIP>" 
FILENAME_JS="nodi.js"

 

cd /home/ubuntu/
sudo ./geth_1_13_4/geth  \
	--datadir node2 \
	--networkid 10002 \
	--allow-insecure-unlock \
	--unlock $PUB_ADDR \
	--http \
	--port 30315 \
	--http.addr $PRIVATE_IP_ADDR \
	--http.port 8547 \
	--nat extip:$PUBLIC_IP_ADDR \
	--http.corsdomain '*' \
	--http.vhosts '*' \
	--http.api admin,eth,miner,net,txpool,personal,web3 \
	--syncmode full \
	--ipcdisable \
	--mine \
	--miner.etherbase $PUB_ADDR \
	--password "pwd.txt" \
	--bootnodes "enr:-KO4QFxe2Bz7vqEJogpPc6Q5IuKbhWFNF3zRHo4iyEbZ3-qeNt1F7ygT815Tr9nDXg9rIjhzOm1rhWFefRq0Lb0W16mGAYtY0JmNg2V0aMfGhH56CP6AgmlkgnY0gmlwhDbZMniJc2VjcDI1NmsxoQNcvmg4pL-sHzn00Tvg3VNuEA_uOdK5KxyOe2yRoeR8YoRzbmFwwIN0Y3CCdmqDdWRwgnZq" \  //Here it points to node 1 as indicated by the documentation
	--authrpc.port 8553 \
	console
```

I'm also using truffle to deploy my contract for data notarization for the first time, although I don't think it has much to do with the problem as it works for me, but I'll leave the info anyway:

**trffle_config.js**
```	
myNet: {
      host: "<publicIP Address of Node1>",
      port: 8546,
      network_id: "10002" 
    },
```

I also noticed another very interesting thing. If I execute some transactions and mine some blocks ONLY with node 1 active (as previously said, this is how it works) and subsequently activate node 2, instead of synchronizing with the mined nodes, node 2 goes into BAD BLOCK as soon as the blocks "arrive" nodes mined by node1.

Besides this I noticed that if I run `admin.peers` on node2 before the nodes previously mined by node1 arrive, it still returns node1 and this makes me understand that initially a synchronization occurs, but when the nodes are read and it occurs this error, `admin.peers` becomes empty = []

If you need more information, just tell me.

Can someone help me?

**Comment by holiman** [comment]
I think it was more or less resolved by this comment in the earlier thread: 

> As far as I can tell, the node which generated this block (block 28) is corrupt. Perhaps you should do a disk-check and/or a RAM-check.

Check the RAM and the disk of that machine -- it has produced an erroneous block. If you are using the same machine now, it's not (very) surprising if it happens again (now on block 1)

**Comment by Alessandro-Cavaliere** [comment]
Thank you for your input. After conducting numerous tests, I have pinpointed that the issue arises from nodes being hosted on separate machines under AWS EC2. Interestingly, when I ran the blockchain locally with nodes on the same machine, everything functioned as expected. However, replicating this setup on a distributed network under AWS results in synchronization problems.

This discrepancy indicates that the problem may not be related to the hardware integrity of the machine that generated block 28, as initially suggested. Instead, the challenges with synchronization seem to be tied to the distributed nature of our setup on AWS EC2.

Do you have any thoughts on this?

**Comment by Alessandro-Cavaliere** [comment]
I mean these AWS servers are in different zones. In any case, I don't think they are memory problems, the memory is all free, it has been cleaned, I have done a configuration of the Geth nodes from scratch several times. 
I don't know what else to try anymore.

**Comment by holiman** [comment]
Yes, so for linux, here is some info 
- https://superuser.com/questions/171195/how-to-check-the-health-of-a-hard-drive
- https://askubuntu.com/questions/59064/how-to-run-a-checkdisk

I'd try `badblocks`, `smartctl` and `fsck`. 

Mem checks might be more difficult (https://askubuntu.com/questions/343114/how-to-check-for-errors-in-ram-via-ubuntu), don't know if AWS allows you do to ram-tests during bootup, but otherwise perhaps you could try `memtester`?

Those are my suggestions.

**Comment by Alessandro-Cavaliere** [comment]
> Yes, so for linux, here is some info
> 
> * https://superuser.com/questions/171195/how-to-check-the-health-of-a-hard-drive
> * https://askubuntu.com/questions/59064/how-to-run-a-checkdisk
> 
> I'd try `badblocks`, `smartctl` and `fsck`.
> 
> Mem checks might be more difficult (https://askubuntu.com/questions/343114/how-to-check-for-errors-in-ram-via-ubuntu), don't know if AWS allows you do to ram-tests during bootup, but otherwise perhaps you could try `memtester`?
> 
> Those are my suggestions.

Updates: I did all the tests you asked for and no malfunctions or poor memories came up. I tried resetting my machines on AWS and tried getting the two nodes on the two machines to communicate.

Unfortunately the problem persists. I also carried out other tests, using a local node and trying to make it point to my AWS machine. Exact same problem.

I'm stuck

**Comment by Alessandro-Cavaliere** [comment]
I solved the problem!!

I followed a guide on Udemy for setting up a network using Amazon AWS and thanks to it I made several additions and changes to my previous configuration:

First of all, in a Linux environment it was recommended to put all the material in the `/opt` folder instead of `/home/ubuntu`.

An important addition was to use the config.toml configuration file following the documentation: [](https://geth.ethereum.org/docs/fundamentals/config-files)

I inserted the enodes of all the nodes inside the `StaticNodes = [] field`

in the .sh file you find above, the guide recommended eliminating some flags in my specific case such as `--nat extip`, `--ipcdisable` and `--bootnodes` and recommended adding these other flags:
`--congif ./config.toml`
`--maxpeers 25`

Now, considering my old problem and this new configuration, could you give me a reason why that BAD BLOCK error always came out? I'm very curious. I hypothesized there is some sort of incorrect generation of the genesis block, but I'm not sure and I'd be happy to hear yours

**Comment by WonderfulFull** [comment]
try to run the node with `--tries-verify-mode full`

**Comment by lichuang2015** [comment]
Hi @Alessandro-Cavaliere , just curious, could you share if you resolved the bad block issue?

**Comment by Ngamesee00** [comment]
[](url)
