### ISSUE TITLE
Fatal: failed to write genesis block: genesis has no chain configuration

### ISSUE THREAD

**Issue by dbe** [ethereum/go-ethereum#7201]
#### System information

Geth version: 1.6.0-unstable-1018bf6a
OS & Version: OSX 10.11.2

It looks like the 'config' attribute of the Genesis struct is required when setting up a new blockchain using the "geth init" command. As of now, no tutorials, including the official ones suggest you pass in a config attribute in your genesis.json file. 

#### Expected behaviour

geth init works properly

#### Actual behaviour

geth init throws error: "Fatal: failed to write genesis block: genesis has no chain configuration"

#### Steps to reproduce the behaviour

call "geth init genesis.json" where your genesis.json file does not include a "config" attribute. 

#### Backtrace

````
geth --identity "MyNodeName" --rpc --rpcport "8080" --rpccorsdomain "*" --datadir "/tmp/dev-geth/" --port "30303" --nodiscover --rpcapi "db,eth,net,web3" --networkid 1999 init CustomGenesis.json

WARN [03-26|15:18:56] No etherbase set and no accounts found as default

INFO [03-26|15:18:56] Allocated cache and file handles         database=/tmp/dev-geth/geth/chaindata cache=128 handles=1024

Fatal: failed to write genesis block: genesis has no chain configuration
````

**Comment by fjl** [comment]
Config being required was a design decision that I made when improving the genesis loader. If the block doesn't define configuration, what should the fork switch-over blocks be? We could set them all to zero, but that would create problems if you created your private chain with one version of geth and then ran `geth init` with a later version that supports a new hard fork.

**Comment by fjl** [comment]
I will improve documentation for now, and we'll decide about this issue before 1.6.0 is released.

**Comment by karalabe** [comment]
I think saying "config is needed from now on" is an acceptable route if we make a clear documentation how it works. And perhaps add a link to the error message where users can read more.

**Comment by fjl** [comment]
I have updated https://github.com/ethereum/go-ethereum/wiki/Private-network.

**Comment by karalabe** [comment]
We have a section in our readme. I really think we should put these stuff in there. The wiki pages are a mess currently.

**Comment by mavstronaut** [comment]
I found the only config that was actually needed was setting a path to the genesis block file. Thanks for updating the docs, I don't remember which tutorial guided me through the first time any more

**Comment by beatrizsanchez** [comment]
I don't know if this is related to the random handshakes that are happening in a private network as described by John [here](http://ethereum.stackexchange.com/questions/13187/private-network-handshaking-with-external-pools/13405). I am having the same issue using a unique networkId, a custom genesis file (with the configuration update you mention in [Private Network documentation](https://github.com/ethereum/go-ethereum/wiki/Private-network)), yet this does not seem to avoid the random handhsakes that are diplayed when when I run `admin.peers` several times secuentially:
```
> admin.peers
[{
    caps: ["eth/62", "eth/63", "par/1", "par/2"],
    id: "78129e171bb7484a00c972caf0771e930d1db8a7c693e582797bd7ff86951eb0d17c4c269d63a91920f8a0c9bd48f317dab63ff334c31b99f6ae97c33f1d0528",
    name: "Parity/v1.5.11-stable-f067f12-20170314/x86_64-linux-gnu/rustc1.15.1",
    network: {
      localAddress: "172.17.0.2:30303",
      remoteAddress: "177.54.152.145:21080"
    },
    protocols: {
      eth: "handshake"
    }
}]
> admin.peers
[]
> admin.peers
[]
> admin.peers
[]
> admin.peers
[{
    caps: ["eth/63"],
    id: "2edaca1f0fcbcbcfddd295f4ad9379cb4a824a718eb05e67a7a148881342c28f0c3e8c761ea8128b55a8c537bf0dacd30c288294e20a690a0d23160b2d1d5244",
    name: "Geth/v1.5.9-stable/windows/go1.7.4",
    network: {
      localAddress: "172.17.0.2:44596",
      remoteAddress: "82.119.101.174:30303"
    },
    protocols: {
      eth: "handshake"
    }
}]
> admin.peers
[]
> admin.peers
[]
```

Would the use of unique "config" parameters in the genesis file help making the network private?

**Comment by fjl** [comment]
@beatrizsanchez this is unrelated. admin.peers sometimes contains peers which are in the negotiation phase. They will be disconnected if the genesis does not match.

**Comment by karalabe** [comment]
I guess this is fixed?

**Comment by Snorlock** [comment]
You should really update the readme aswell: https://github.com/ethereum/go-ethereum
That is currently not working

**Comment by clawoflight** [comment]
@fjl Could you elaborate on this?

> If the block doesn't define configuration, what should the fork switch-over blocks be? We could set them all to zero, but that would create problems if you created your private chain with one version of geth and then ran geth init with a later version that supports a new hard fork.

What should I use when creating a private chain?

**Comment by karalabe** [comment]
It's fine if you set all your fork blocks to zero for a new private network.

@fjl was saying that we ourselves cannot default to zero automatically, because if you have a private network that's running for 3 weeks, and then we release a new fork (e.g. Metropolis) with a default block number of 0, it will invalidate your 3 week old chain. So you need to manually add the metro fork block to your genesis at whatever you feel best and run your nodes with the new configs from that point onward.

**Comment by clawoflight** [comment]
@karalabe Thanks, but I still don't understand.

- How would I see that something stops working?
- How do I add a fork block to my genesis block?
- What would I do afterwards? Do I need to re-init the chain?
